[msan][test] Add regression tests for svcount.ll
target("aarch64.svcount") is not properly supported by MSan, and will lead to a clang crash:
```
fatal error: error in backend: Cannot implicitly convert a scalable size to a fixed-width size in `TypeSize::operator ScalarTy()`
```

This commit adds two test cases: a full test case for tracking any future improvements to the instrumentation, and a manually reduced test case to show the crash.

Forked from llvm/test/CodeGen/AArch64/sme-aarch64-svcount.ll