Handle tag types and complain about bad merges in C/Objective-C mode
Summary:
Take `struct Z {...}` defined differently and imported from both modules
X and Y. While in C/ObjC mode, clang used to pick one of the definitions
and ignore the other even though they might not be structurally
equivalent.

- Instead of using the structural equivalence code for checking
compatibility, use the ODR hash mechanism. This should significantly
speed up the checks.
- Hook the necessary name lookup bits to allow this logic in C.
- Teach diagnoseOdrViolations to check the differences.

Instead of silently compiling, clang now emits:

In module 'Y' imported from t.m:2:
./y.h:3:10: error: 'Z::m' from module 'Y' is not present in definition
of 'struct Z' in module 'X'
  double m;
         ^
./x.h:3:7: note: declaration of 'm' does not match
  int m;
      ^

rdar://problem/56764293

Reviewers: rsmith, arphaman, vsapsai, martong, jdoerfert

Subscribers: rnkovacs, jkorous, dexonsmith, ributzka, cfe-commits

Tags: #clang

Differential Revision: https://reviews.llvm.org/D71734