[lldb] Implement swift diagnostic for non-captured vars in "expr"
This commit implements the same diagnostic that was previously
implemented for frame var. The strategy here is slightly different due
to how expression evaluation works.

We have to pattern match this diagnostic from the compiler:

```
error: <EXPR>:6:1: cannot find 'NAME' in scope
1 + NAME
    ^~~~
```

If we find it, we trigger the usual search for a variable named `NAME`.
If it is found, the diagnostic is replaced with:

```
error: <EXPR>:6:5: Current frame is a closure.
A variable named 'NAME' exists in function 'foo(_:)', but it was not captured.
Hint: the variable may be available in a parent frame.
1 + NAME
    ^~~~
```

Implementation note: the pattern matching could be a _lot_ simpler if we
don't insist on replacing the original diagnostic and, instead, append
to it.

(cherry picked from commit 13a1eb2116187d7d7339af5de3b1fa12a3e9623a)