Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit dacdefb935f40931f1789a85845e4b6dcfc5c77d.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'