Revert "[LLD] [COFF] Implement a GNU/ELF like -wrap option"
This reverts commit 7ea72c9146dbadea17de8f344668ed224d221e20.

Breaks Windows builds.

C:\src\llvm-mint\lld\COFF\Symbols.cpp(26,1): error: static_assert failed due to requirement 'sizeof(lld::coff::SymbolUnion) <= 48' "symbols should be optimized for memory usage"
static_assert(sizeof(SymbolUnion) <= 48,