Revert "Fix attr docs from previous no-unique-adderss change (#67195)"
This reverts commit 5e9ed3cca1d18426dbb49f76155743769cd6ef02.

It caused
```
error: Record `NoUniqueAddress', field `Documentation' exists but does not have a list value
```