[lldb][test] Rewrite Watchpoint/SetErrorCases as API test
This test is randomly failing on macOS bots with this error:
```
error: Command requires a process which is currently stopped.
```

There is no test logic in shell tests that can diagnose what is going
on with the process, so this patch rewrites this test as an API test
where we have better error handling.