[lldb] Improve error when redefining persistent vars
A redefinition of a persistent variable currently yields the following
error:

```
(lldb) expr int $var = 13423
error: redefinition of persistent variable '$var'
error: Internal error [IRForTarget]: Couldn't rewrite the creation of a persistent variable
```

The internal error makes this look like it's an LLDB bug, but this is
really just a normal error. This patch is mostly just a bunch of error
propagation logic so we actually know what went wrong in the calling
logic.

This patch also adds some errors messages where we previously only
returned `false` (as returning an actual error message is now mandatory
for all code paths). I don't know if we can actually test any of these
as most of this is only code that is reachable if there is an actual
LLDB or system bug.

assisted-by: claude