Revert "[Tooling/Inclusion] Handle std::get symbol."
This reverts commit 6dc393ea1bb22c7ff6ad343ea30963335879fe98.

Causing many clangd test breakages, similar to:

error: no matching constructor for initialization of 'llvm::SmallVector<clang::tooling::stdlib::Header>'
                : llvm::SmallVector<clang::tooling::stdlib::Header>(
                  ^