Try to fix Windows lambda capture build error
(Cherry-picked from amd-gfx-upstream+npi)

Try to fix this Windows build error:
GCNHazardRecognizer.cpp(1159): error C3493: 'NoHazardWaitStates' cannot be implicitly captured because no default capture mode has been specified

Change-Id: Ie50ed89453bef2b08c34e033fc4034e9e1fc3387