Swift: Fix the Windows build
The implicit conversion from `nullptr_t` to `bool` is not permitted on Windows.

```
lldb\source\Plugins\Language\Swift\SwiftUnsafeTypes.cpp(316,12): error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
    return nullptr;
           ^~~~~~~
```

Explicit return a `false` instead.

(cherry picked from commit a13459550e48f25328760f4ed9cd0fe28fbf9bb2)