[AsmPrinter] Fix an unused variable warning
This patch fixes:

  llvm/lib/CodeGen/AsmPrinter/DwarfFile.cpp:109:10: error: unused
  variable 'Ret' [-Werror,-Wunused-variable]