[flang-rt] Fix runtime/environment.cpp compilation on FreeBSD
`runtime/environment.cpp` doesn't compile on FreeBSD:

```
runtime/environment.cpp:115:47: error: use of undeclared identifier 'RTLD_DEFAULT'
  115 |   auto envpp{reinterpret_cast<char ***>(dlsym(RTLD_DEFAULT, "environ"))};
      |                                               ^~~~~~~~~~~~
```

`<dlfcn.h>` needs to be included.

Tested on `x86_64-pc-freebsd15.1` and `x86_64-pc-linux-gnu`.