[heap.py] Add missing declaration for malloc_get_all_zones
The evaluation context isn't guaranteed to have this declaration.

Fixes "error: use of undeclared identifier 'malloc_get_all_zones'" bugs.

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@369684 91177308-0d34-0410-b5e6-96231b3b80d8
apple-llvm-split-commit: 0b6087407746abe1af95367bd491863893c3d235
apple-llvm-split-dir: lldb/