Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit 4c214c27cdbb0a64bcc7486ce73b3f4509941916 and
03ddfd4df88ce002c176bbe3c46a5ffc58aac32c.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!