Revert "Move DroppedVariableStatsIRTest.cpp to CodeGen folder"
This reverts commit 2eb465a698e6b321fbd2d052ddcd42752bec92c1.

Revert "Reland a3eb0270d3381afe6621770ef2d1a9ef9f736f85 (#119650)"

This reverts commit a25fba37ff69bd70659ffff6d00a905c28606419.

This is because the clang-ppc64le-linux-multistage bot breaks with error

undefined reference to `vtable for llvm::DroppedVariableStatsIR'