[llvm] Upgrade ARM data layouts that are missing Fi8
Such as the ones in https://github.com/llvm/llvm-test-suite/tree/main/Bitcode/simd_ops,
which started failing to compile after
https://github.com/llvm/llvm-project/pull/224012
stopped us overriding the module data layout.

fatal error: error in backend: Can't create a MachineFunction using a Module with a Target-incompatible DataLayout attached
  Target DataLayout: e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64
  Module DataLayout: e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64

The old layout is p32:32-i64, the new is p32:32-Fi8-i64.

In this change I have added this case to the data layout
upgrades. If there's no p32:32, the layout is not changed,
also if there is already a "Fi" or "Fn" in the layout.