[NVPTX] Remove unused private field in NVVMIntrRange.cpp (NFC)
/llvm-project/llvm/lib/Target/NVPTX/NVVMIntrRange.cpp:33:12:
error: private field 'SmVersion' is not used [-Werror,-Wunused-private-field]
  unsigned SmVersion;
           ^
1 error generated.