[flang-rt][test] Fix Exceptions.cpp compilation on FreeBSD (#219709)
The `Runtime/Exceptions.cpp` test doesn't compile on FreeBSD:

```
unittests/Runtime/Exceptions.cpp:41:10: error: no type named '__fesetenv_int' in namespace 'std'
   41 |     std::fesetenv(&saved_);
      |     ~~~~~^
/usr/include/fenv.h:158:22: note: expanded from macro 'fesetenv'
  158 | #define fesetenv(a)             __fesetenv_int(a)
unittests/Runtime/Exceptions.cpp:41:20: error: declaration of reference variable 'saved_' requires an initializer
   41 |     std::fesetenv(&saved_);
      |                    ^~~~~~
```

`<fenv.h>` defines

```
#define fesetenv(a)             __fesetenv_int(a)
```

Fixed by removing the namespace qualifier, matching other cases.

Tested on `x86_64-pc-freebsd15.1` and `x86_64-pc-linux-gnu`.

(cherry picked from commit a1c69c122169370c2203a67e59b1a1a94f2f2669)