[flang] Fix compilation errors due to new clang template requirements
Since https://github.com/llvm/llvm-project/pull/80801 clang requires
a template argument list after the use of the template keyword.

https://lab.llvm.org/buildbot/#/builders/176/builds/10230

error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]

This fixes the instances found by the AArch64 Linux builds.