[NVPTX] Add unreachable for TMA Inst Printer
This patch adds the llvm_reachable() for TMA
reduction opcode printer method.

We had this inside the default-case leading to
warning below (and hence was removed):
error: default label in switch which covers all enumeration values
       [-Werror,-Wcovered-switch-default]

Signed-off-by: Durgadoss R <durgadossr@nvidia.com>