stage3 (generic-hardening-mode-fast-with-abi-breaks, llvm-premerge-libcxx-next-runners)
```
 # .---command stderr------------
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/associative/multimap/multimap.cons/copy_assign.pass.cpp:307:17: error: static assertion expression is not an integral constant expression
  # |   307 |   static_assert(test());
  # |       |                 ^~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__iterator/wrap_iter.h:60:95: note: constexpr evaluation hit maximum step limit; possible infinite loop?
  # |    60 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX14 reference operator*() const _NOEXCEPT { return *__i_; }
  # |       |                                                                                               ^
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__iterator/bounded_iter.h:123:12: note: in call to 'this->__current_.operator*()'
  # |   123 |     return *__current_;
  # |       |            ^~~~~~~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__algorithm/remove.h:34:9: note: in call to '__first.operator*()'
  # |    34 |         *__first = std::move(*__i);
  # |       |         ^~~~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/associative/multimap/multimap.cons/copy_assign.pass.cpp:51:16: note: in call to 'remove<std::__bounded_iter<std::__wrap_iter<void **>>, std::__tree_node<std::__value_type<int, int>, void *> *>({{&{*new void *[256]#641}[34]}, {&{*new void *[256]#641}[0]}, {&{*new void *[256]#641}[256]}}, {{&{*new void *[256]#641}[57]}, {&{*new void *[256]#641}[0]}, {&{*new void *[256]#641}[256]}}, ptr)'
  # |    51 |     auto res = std::remove(allocs_->begin(), allocs_->end(), ptr);
  # |       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__memory/allocator_traits.h:289:5: note: in call to '__a.deallocate(&{*new std::__tree_node<std::__value_type<int, int>, void *>[1]#554}[0], 1)'
  # |   289 |     __a.deallocate(__p, __n);
  # |       |     ^~~~~~~~~~~~~~~~~~~~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__tree:1531:7: note: in call to 'deallocate(orig.__tree_.struct (anonymous struct at /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__tree:874:3).__node_alloc_, &{*new std::__tree_node<std::__value_type<int, int>, void *>[1]#554}[0], 1)'
  # |  1531 |       __node_traits::deallocate(__alloc_, __ptr, 1);
  # |       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__tree:1533:7: note: (skipping 4 calls in backtrace; use -fconstexpr-backtrace-limit=0 to see all)
  # |  1533 |       (*this)(std::__static_fancy_pointer_cast<__node_pointer>(__right));
  # |       |       ^
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/build/generic-hardening-mode-fast-with-abi-breaks/libcxx/test-suite-install/include/c++/v1/__tree:955:5: note: in call to 'this->destroy(&{*new std::__tree_node<std::__value_type<int, int>, void *>[1]#541}[0])'
  # |   955 |     destroy(__root());
  # |       |     ^~~~~~~~~~~~~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/associative/multimap/multimap.cons/copy_assign.pass.cpp:237:9: note: in call to 'orig.__tree_.~__tree()'
  # |   237 |     Map orig(rhs_alloc);
  # |       |         ^~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/associative/multimap/multimap.cons/copy_assign.pass.cpp:237:9: note: in call to 'orig.~multimap()'
  # |   237 |     Map orig(rhs_alloc);
  # |       |         ^~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/associative/multimap/multimap.cons/copy_assign.pass.cpp:281:5: note: in call to 'test_alloc<tracking_allocator<std::pair<const int, int>>, AssertEmpty>(lhs_allocs, rhs_allocs, {&lhs_allocs, &rhs_allocs})'
  # |   281 |     test_alloc<tracking_allocator<std::pair<const int, int> > >(
  # |       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # |   282 |         lhs_allocs, rhs_allocs, AssertEmpty(lhs_allocs, rhs_allocs));
  # |       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # | /home/gha/actions-runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/associative/multimap/multimap.cons/copy_assign.pass.cpp:307:17: note: in call to 'test()'
  # |   307 |   static_assert(test());
  # |       |                 ^~~~~~
  # | 1 error generated.
  # `-----------------------------
  # error: command failed with exit status: 1
```