Merging r260839: ------------------------------------------------------------------------ r260839 | dim | 2016-02-14 01:26:32 +0100 (Sun, 14 Feb 2016) | 8 lines
Fix lib/tsan/go/buildgo.sh for FreeBSD after r243051.

FreeBSD also needs to have sanitizer_linux_libcdep.cc included,
otherwise linking will fail with "undefined reference to
`__sanitizer::GetRSS()'".

While here, tabify the FreeBSD part, similar to the other parts.

------------------------------------------------------------------------

llvm-svn: 261123