[ARM] fix `r14` aliasing `lr` on `thumb-1` (#225746)
Since https://github.com/llvm/llvm-project/pull/179740 `r14` is accepted
as an alias for `lr`, which works on `arm` and `thumb-2` targets, but
not on `thumb-1`

https://godbolt.org/z/WEEjMMj93

```llvm
; -mtriple=thumbv6m-none-eabi
define i32 @read_r14() nounwind {
start:
  %1 = tail call i32 asm sideeffect alignstack "", "=&{r14},~{cc},~{memory}"()
  ret i32 %1
}
```

Gives

```
error: register 'LR' allocated for constraint '{r14}' does not match required type
```

Apparently on `thumb-1` the register class of `lr` is not the same as
the class of `i32`. So, just truly make `{r14}` an alias for `{lr}`.

---

Found via https://github.com/rust-lang/rust/issues/163173.

We should backport this if we can.

(cherry picked from commit b028ea82203a25d29bf469286319a0e7b3daa1d5)