[HLSL][clang][Driver] Fix error when using the option -fcgl in --driver-mode=dxc.
When -fcgl is set in --driver-mode=dxc, both -S and -emit-llvm are currently enabled.

This results in the following error:

  error: '-S' action ignored; '-emit-llvm' action specified previously.

This change fixes the issue by not rendering -S in RenderHLSLOptions.

Additionally, a test has been added to ensure that enabling -fcgl does not trigger any diagnostics