[compiler-rt] Allow to build on CYGWIN
If you try to build compiler-rt on CYGWIN, you will get message:
error: Unsupported target
Adding support for this platform just need to add testing if __CYGWIN__ is defined into lib\builtins\int_lib.h.