Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit 196a10d1e4918aa5d30bc4c6d0128ea32a06cc1f.

A bot is broken