[BPF] Support signed division at cpu v1 with constant divisor
The motivation example likes below
  $ cat t1.c
  struct S {
    int var[3];
  };
  int foo1 (struct S *a, struct S *b)
  {
      return a - b;
  }

For cpu v1/v2/v3, the compilation will fail with the following
errors:
  $ clang --target=bpf -O2 -c t1.c -mcpu=v3
  t1.c:4:5: error: unsupported signed division, please convert to unsigned div/mod.
      4 | int foo1 (struct S *a, struct S *b)
        |     ^
  1 error generated.

The reason is that sdiv/smod is supported at -mcpu=v4.
At cpu v1/v2/v3, only udiv/umod is supported.

But the above example (for func foo1()) is reasonable common and
user has to workaround the compilation failure by using udiv with
conditionals.

For x86, for the above t1.c, compile and dump the asm code like below:
  $ clang -O2 -c t1.c && llvm-objdump -d t1.o
  0000000000000000 <foo1>:
       0: 48 29 f7                      subq    %rsi, %rdi
       3: 48 c1 ef 02                   shrq    $0x2, %rdi
       7: 69 c7 ab aa aa aa             imull   $0xaaaaaaab, %edi, %eax # imm = 0xAAAAAAAB
       d: c3                            retq

Basically sdiv can be replaced with sub, shr and imul. Latest gcc-bpf
is also able to generate code similar to x86 with -mcpu=v1.
See https://godbolt.org/z/feP9ETbjj

So let us add clang support for sdiv (constant divisor) as well at
-mcpu=v1. But we still want to keep udiv untouched at -mcpu=v1.
One more parameter "bool IsSigned" is added to isIntDivCheap().
The "IsSigned" parameter is used only by BPF backend to ensure
udiv not impacted.

Note that only 32-bit sdiv (constant divisor) can be converted into
sub/shr/imul. 64-bit sdiv (constant divisor) cannot be converted
since bpf does not support 64-bit multiplication without potential
overflow.