Remove const volatile bool tests
These now trigger errors in C++26:

> error: volatile-qualified parameter type 'const volatile bool' is deprecated [-Werror,-Wdeprecated-volatile]

Since std::variant no longer treats const volatile bool specially, just
remove the lines.