Remove extra ; to fix CI build error
The CI build has started failing because of this ; which has been
there for quite some time:

  /home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/lib/CodeGen/ExpandFp.cpp:1134:36: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-sem
  1134 |     : TM(TM), OptLevel(OptLevel) {};

Remove it.