Revert "[RISCV][NFC] Make generated intrinsic records more human-readable (#133710)"
This reverts commit 8740ff4050d417b77cada98865b2c769838d9024.

Error: "declaration of ‘clang::RISCV::RequiredExtensions
{anonymous}::SemaRecord::RequiredExtensions’ changes meaning of
‘RequiredExtensions’ [-fpermissive]"