[mlir][tosa] Fix validation of `dim` op when reliant on datatype extension
For example:
```
error: 'tosa.dim' op illegal: requires [bf16, shape] but not included in the profile compliance [shape]

    %0 = tosa.dim %arg0 {axis = 4 : i32} : (tensor<4x5x8x8x6x4xbf16>) -> !tosa.shape<1>
```
Here dim requires support to be declared for the BF16 and SHAPE extensions, but only SHAPE was specified
in the op declaration.

Change-Id: I5c986d6763904483c68da0e1c2aa9923947d2c3f