[compiler-rt] [test] Avoid error printouts if os.sysconf is missing
This avoids dozens of instances of benign error messages being
printed when running the tests on e.g. Windows:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'os' has no attribute 'sysconf'