[Vectorize] Fix a warning
This patch fixes:

  llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:33452:18: error:
  lambda capture 'Limit' is not required to be captured for this use
  [-Werror,-Wunused-lambda-capture]