[test] Create the `swiftpr` test category and populate it
This test category is for Swift smoke tests run during pull-request
testing. It must only contain reliable, swift-related tests: failing,
expected-failing, unexpected-failing, or other flaky tests do not belong
in this category.

Initial results:

./swift/utils/build-script --release --skip-build-benchmarks
--skip-test-cmark --skip-test-swift --lldb --lldb-use-system-debugserver
--lldb-build-with-cmake --test --lldb-test-swift-only

Test Methods:        256
Reruns:                0
Success:              29
Expected Failure:      0
Failure:               0
Error:                 0
Exceptional Exit:      0
Unexpected Success:    0
Skip:                227
Timeout:               0
Expected Timeout:      0

(cherry picked from commit eec829ecbd16c64480e75835cb12f84c9bdb60bc)

apple-llvm-split-commit: 9301aa25fe060646a1bd9a8a0efc158f05b49b9e
apple-llvm-split-dir: lldb/