Use "_LIBCPP_HAS_MUSL_LIBC" directly
Instead of `#if defined(_LIBCPP_HAS_MUSL_LIBC)`, we can rely on
`#if _LIBCPP_HAS_MUSL_LIBC` directly.

This should address these failures:

	  # .---command stdout------------
	  # | /__w/llvm-project/llvm-project/build/frozen-cxx03-headers/libcxx/test-suite-install/include/c++/v1/__locale_dir/support/linux.h:98:6: error: '_LIBCPP_HAS_MUSL_LIBC' is always defined to 1 or 0. [libcpp-internal-ftms,-warnings-as-errors]
	  # |    98 | #if !defined(_LIBCPP_HAS_MUSL_LIBC)
	  # |       |      ^
	  # | /__w/llvm-project/llvm-project/build/frozen-cxx03-headers/libcxx/test-suite-install/include/c++/v1/__locale_dir/support/linux.h:108:6: error: '_LIBCPP_HAS_MUSL_LIBC' is always defined to 1 or 0. [libcpp-internal-ftms,-warnings-as-errors]
	  # |   108 | #if !defined(_LIBCPP_HAS_MUSL_LIBC)
	  # |       |      ^
	  # `-----------------------------