Revert "Add symbol locator time for each module in statistics (#134563)"
This reverts commit 26d6012a33f289c61b333e37fb86fd08dd2f64da.

Multiple buildbot failures have been reported:
https://github.com/llvm/llvm-project/pull/134563

The build fails with:

  lldb/source/Target/Statistics.cpp:75:39: error: use of undeclared
  identifier 'num_symbols_loaded'