Revert "[Clang] Add warnings when mixing different charN_t types (#138708)"
breaks build of rocSOLVER
[2025-05-15T22:58:37.770Z] /home/jenkins/agent/workspace/compiler-psdb-amd-staging/Libs/rocSOLVER/build/deps/gtest-1.11.0-src/googletest/include/gtest/gtest-printers.h:474:35: error: implicit conversion from 'char16_t' to 'char32_t' may change the meaning of the represented code unit [-Werror,-Wcharacter-conversion]
[2025-05-15T22:58:37.770Z]   474 |   PrintTo(ImplicitCast_<char32_t>(c), os);
[2025-05-15T22:58:37.771Z]       |           ~~~~~~~~~~~~~           ^
[2025-05-15T22:58:38.975Z] 1 error generated.

This reverts commit 381a649fb991eadb0c594de2d8b6166fcc11345a.