[llvm-dwp] Default output file name to <exec>.dwp when -o is omitted
When invoked with -e <exec> but no -o, GNU dwp writes to <exec>.dwp,
whereas llvm-dwp fails with:

    $ /home/smarchi/build/llvm-project/debug/bin/llvm-dwp -e rocm-dwp-test
    while processing dwarf streamer init:
    error: : No such file or directory

I think it would be useful to match GNU dwp's behavior here.  Fix it by
computing a default output filename.

Implementation detail: when passing multiple executable (the `-e` flag),
GNU dwp just remembers the last one (silently drops the previous ones).
So, the default output filename is naturally based on the last
executable.  llvm-dwp, on the other hand, processes them all (collects a
list of .dwo file from all).  I think it wouldn't make sense, if the
user specified multiple executables, to name the output file after one
arbitrary executable.  Therefore, I made it such that a default
filename is used if the user specifies exactly one executable.

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>