[Sema] Fix a warning
This patch fixes:

  clang/lib/Sema/AnalysisBasedWarnings.cpp:2269:21: error: unused
  variable 'subExpr' [-Werror,-Wunused-variable]

(cherry picked from commit 73ff017c9b39d8a1ecc350f0572e3274dd4c9146)