Revert "[ubsan] Simplify ubsan_GetStackTrace"
This reverts commit 9f731bc7e1d4d41889abe07ba0f638a9286af2c7.

I don't quite understand why, but this causes a linker error for
me and a number of buildbots:

/home/npopov/repos/llvm-project/compiler-rt/lib/ubsan/../sanitizer_common/sanitizer_stacktrace.h:130: error: undefined reference to '__sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int)'