Revert "[ADT] Apply fixes from modernize-type-traits (NFC)"
This reverts commit 10da732567f20c496ba02a4512a58a40dccfbbf0 because it
breaks the modules build:

  STLFunctionalExtras.h:54:3: error:
  'llvm::function_ref<std::__1::optional<std::__1::basic_string<char>>
  (llvm::StringRef, llvm::StringRef)>::function_ref' from module
  'LLVM_Utils.ADT.STLFunctionalExtras' is not present in definition of
  'llvm::function_ref<std::__1::optional<std::__1::basic_string<char>>
  (llvm::StringRef, llvm::StringRef)>' in module
  'LLVM_Utils.ADT.STLFunctionalExtras'

https://green.lab.llvm.org/green/view/LLDB/job/lldb-cmake/53806/