[APINotes] Explicitly include Bitstream/BitCodes.h
This fixes a modules issue:

error: declaration of 'bitc' must be imported from module
'LLVM_Bitcode.LLVMBitCodes' before it is required CONTROL_BLOCK_ID =
llvm::bitc::FIRST_APPLICATION_BLOCKID,

rdar://52785864

apple-llvm-split-commit: d00582d5dc4bc5b2ebd823d9a0293d4a8107d157
apple-llvm-split-dir: clang/