[lldb] Add zlib to version -v output
I know this is required for at least one feature, because TestSectionAPI.py
has failures if zlib isn't enabled. So I think it's useful for users to be
able to check.

Now that it's in the config, I have also used it to make a test
annotation so we don't get the failure in TestSectionAPI.py when
zlib is disabled.

Which for future reference was:
Traceback (most recent call last):
  File "/home/davspi01/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 452, in wrapper
    return func(self, *args, **kwargs)
  File "/home/davspi01/llvm-project/lldb/test/API/python_api/section/TestSectionAPI.py", line 67, in test_compressed_section_data
    self.assertEqual(section_data, [0x20, 0x30, 0x40, 0x50, 0x60, 0x70, 0x80, 0x90])
AssertionError: Lists differ: [] != [32, 48, 64, 80, 96, 112, 128, 144]

As it failed to decode the compressed section.