[libc++] Don't use `copy_file_impl_fstream` when not declared
`copy_file_impl_fstream` is declared and defined only under
`_LIBCPP_FILESYSTEM_NEED_FSTREAM` (which additionally requires
`_LIBCPP_HAS_LOCALIZATION`), and then used in a `copy_file_impl`
variant under a disjoint set of conditions. This causes any build that
disables localization and elects this variant of `copy_file_impl`, as is
currently the case when targeting wasi, to fail with a generic compiler
error:

```
error: use of undeclared identifier 'copy_file_impl_fstream'
```

Instead, since this particular `copy_file_impl` implementation merely
forwards to `copy_file_impl_fstream`, tweak its gating condition such
that the aforementioned configuration hits the dedicated fallback
branch, which offers a somewhat clearer error message:

```
\#  error "Unknown implementation for copy_file_impl"
```