[BoundsSafety] Support __single and __unsafe_indexable in template definitions in attribute only mode
Previously code like this would fail to compile:

```
template <class T>
class Ref {
  public:
  T __single ptr;
};

void use() {
  Ref<int*> ok;
}
```

with the following error

```
error: '__single' attribute only applies to pointer arguments
```

This happens because we try to do type checking on the uninstantiated
template which fails because `T` is a `TemplateTypeParmType` and not a
`PointerType`.

In `-fbounds-safety` mode there's no good way to fix this because
`__single` and `__unsafe_indexable` are part of the `PointerType` so the
attribute can't be represented in the AST because there is no
`PointerType`, only a `TemplateTypeParmType`.

However, in `-fexperimental-bounds-safety-attributes` mode `__single`
and `__unsafe_indexable` are represented as type sugar (`AttributedType`).
This means it is possible to add the AttributedType on the
`TemplateTypeParmType` (i.e. adding sugar to the unknown template type).

This patch makes the above code compile in
`-fexperimental-bounds-safety-attributes` mode by

* Removing the error diagnostic when the type being checked in
  `HandleBoundsSafetyPointerTypeAttr(...)` is a `TemplateTypeParmType`
  and we are in `-fexperimental-bounds-safety-attributes` mode.

* Adding `ConstructBoundsSafetyPointerType::VisitTemplateTypeParmTypeLoc`
  so that the `__single` or `__unsafe_indexable` type sugar is applied
  when in `-fexperimental-bounds-safety-attributes` mode.

* Teaching `TreeTransform<Derived>::TransformAttributedType` to check that
  `__single` and `__unsafe_indexable` are being applied to `PointerType`.
  This method is used by the `TemplateInstantiator` class which performs
  template instantiation.

In principle a similar approach could be used to support
`__null_terminated` in template definitions. However, doing so would be
quite complicated and should be handled separately (rdar://152451848).

rdar://152249884