[PowerPC] Restore LiveVariables run before PPCTLSDynamicCallPass
This change is a partial revert of 7818c91f7151. Removing the explicit LiveVariables run
before PPCTLSDynamicCallPass causes a crash on ppc64le -fPIC builds:

  fatal error: error in backend: Use not jointly dominated by defs.

This change was first added in 2016 with an unresolved FIXME. Unfortunately, the
root cause still needs to be understood and investigated, so restore this for
now to fix the broken buildbots.