[llvm][examples] Disable some JIT examples when threading is disabled
This fixes an error on our Armv8 bot:
<...>/RemoteJITUtils.cpp:132:24: error: use of undeclared identifier 'DynamicThreadPoolTaskDispatcher'
  132 |       std::make_unique<DynamicThreadPoolTaskDispatcher>(std::nullopt),
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

These examples require LLVM_ENABLE_THREADS to be ON, and cannot run
otherwise. As a comment says elsewhere:
```
  // Out of process mode using SimpleRemoteEPC depends on threads.
```