[OpenCL] Add cl_khr_fp64 guard for atomic_double/double in cl_ext_float_atomics functions
Fix kernel build when cl_khr_fp64 is not enabled:
opencl-c.h:13785:50: error: unknown type name 'atomic_double'
 13785 | double __ovld atomic_fetch_min(volatile __global atomic_double *, double);
opencl-c.h:13785:67: error: use of type 'double' requires cl_khr_fp64 and __opencl_c_fp64 support
 13785 | double __ovld atomic_fetch_min(volatile __global atomic_double *, double);

This is a regression introduced by 423bdb2b. Before that commit,
__opencl_c_ext_fp64_global_atomic_add was guarded by cl_khr_fp64 in opencl-c-base.h.