Use ::llvm:LogicalResult instead of LogicalResult in FunctionInterfaces.td
Fixed a minor typo, which can cause compile error:

error C3646: 'eraseResult': unknown override specifier