Fix merge issue in amd-gfx-gfx13
Fix build error introduced in 96ce5b1da1d4109ce839a84025f77ae6cab32a49:

llvm/tools/llvm-readobj/ELFDumper.cpp:1654:3: error: expected unqualified-id
  ENUM_ENT(EF_AMDGPU_MACH_AMDGCN_GFX9_GENERIC, "gfx9-generic"),                \
  ^
llvm/tools/llvm-readobj/ELFDumper.cpp:86:3: note: expanded from macro 'ENUM_ENT'
  { #enum, altName, ELF::enum }
  ^
llvm/tools/llvm-readobj/ELFDumper.cpp:1663:26: error: expected expression
    AMDGPU_MACH_ENUM_ENTS,
                         ^
llvm/tools/llvm-readobj/ELFDumper.cpp:1669:26: error: expected expression
    AMDGPU_MACH_ENUM_ENTS,

Change-Id: I961fee544ed101a6bf054e972c7346c1f2623fa7