Revert "[YAML][NFC] precommit wrong test case (#131782)"
This reverts commit b05dec6f4d15d30eed4b1799070f2980b17161d1.

That commit broke compilation with GCC:

../unittests/Support/YAMLIOTest.cpp:1280:20: error: explicit specialization of
template<class T> struct llvm::yaml::MappingTraits’ outside its namespace must u
se a nested-name-specifier [-fpermissive]
 1280 | template <> struct MappingTraits<V> {
      |                    ^~~~~~~~~~~~~~~~