[CUDA][HIP] improve error message for missing cmath
One common error seen in CUDA/HIP compilation is:

fatal error: 'cmath' file not found

which is due to inproper installation of standard C++ libraries.

Since it happens with #include_next, users may feel confusing
which cmath is not found and how to fix it.

Add an error directive to help users resolve this issue.