[offload] Fix link issues when LLVM_LINK_LLVM_DYLIB on
When LLVM_LINK_LLVM_DYLIB is on, link against LLVM (shared library) rather than
individual (static) libraries. Otherwise, global initializers may get called
multiple times as multiple copies of LLVM libraries are loaded.

This typically results in a runtime error such as:

  Error: CommandLine Error: Option ... registered more than once

See related commit ea8bb4d633683f5cbfd82491620be3056f347a02