[flang][cuda] Avoid hlfir.declare verifier error when creating temps
When creating temporaries for implicit transfer, the newly create hlfir.declare
operation was missing some information like the shape and the verifier was
throwing an error. Fix it by making sure we have an ExtendedValue when calling
addSymbol to register the temp.

```
error: loc("cuda-data-transfer.cuf":67:22): 'hlfir.declare' op of array entity
with a raw address base must have a shape operand that is a shape or shapeshift
```