[OpenMP] Added missing MPI include file in Emissary source. (#684)
Fixes smoke-dev mpi-reduce, mpi-allreduce.

Fixes errors of the form EmissaryMPI.h:54:3: error: unknown type name
'MPI_Datatype'.