Revert "[test][Support] Disable CFI-icall for DynamicLibrary Overload test (#202446)" (#202768)
Reverts llvm/llvm-project#202684

This breaks builds with some gcc versions (at least v14).

```
/home/aidengrossman/llvm-project/llvm/unittests/Support/DynamicLibrary/DynamicLibraryTest.cpp:62:32: error: attributes are not allowed on a function-definition
   62 | TEST(DynamicLibrary, Overload) __attribute__((no_sanitize("cfi-icall"))) {
      |                                ^~~~~~~~~~~~~
```