[AArch64] make +dit non-FMV-only (#90987)
Required to fix an llvm-test-suite failure:

    error: expected writable system register or pstate: "msr DIT, x0"