Revert "Implement a new kind of Pass: dynamic pass pipeline"
This reverts commit 8a50f4d0604bb5131ea94099685370f9047d6aa1.

Test  mlir/test/Pass:dynamic-pipeline-fail-on-parent.mlir.test fails
when run with ASAN:

ERROR: AddressSanitizer: stack-use-after-scope on address ...

Reviewed By: bkramer, pifon2a

Differential Revision: https://reviews.llvm.org/D88079