Revert "[llvm-exegesis] Add thread IDs to subprocess memory names (#84451)"
This reverts commit 47302b566b821aafe3fd48d79d76b8d1c0ba0299.

This breaks building LLVM on macOS, failing with

    llvm/tools/llvm-exegesis/lib/SubprocessMemory.cpp:146:33: error: out-of-line definition of 'setupAuxiliaryMemoryInSubprocess' does not match any declaration in 'llvm::exegesis::SubprocessMemory'
    Expected<int> SubprocessMemory::setupAuxiliaryMemoryInSubprocess(