Revert "[FPEnv][X86] Platform-specific builtin constrained FP enablement"
This reverts commit 83f3060a1af0826793ad5f97b43c82b3cdcd502e.

Tests fail:
error: unable to create target: 'No available targets are compatible with triple "x86_64-apple-darwin"'

This happens on clang-hexagon-elf, clang-cmake-armv7-quick, and
clang-cmake-armv7-quick bots.

If anyone has any suggestions on why then I'm all ears.

Differential Revision: https://reviews.llvm.org/D73570

Revert "[FPEnv][X86] Speculative fix for failures introduced by eda495426."

This reverts commit c81b060f59dc878864e43f2948eb9fa812a64cfd.

The speculative fix didn't solve the test failures on Hexagon, ARMv6, and
MSVC AArch64.