[AST] Use explicit type erasure in TypeSourceInfo constructor
When this file is included in a project compiled with GCC 13 -Werror,
compilation fails with the following diagnostic:
  /usr/lib/llvm-17.0/include/clang/AST/TypeLoc.h: In constructor 'clang::TypeSourceInfo::TypeSourceInfo(clang::QualType, size_t)':
  /usr/lib/llvm-17.0/include/clang/AST/TypeLoc.h:245:9: error: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'class clang::TypeSourceInfo'; use assignment instead
  +[-Werror=class-memaccess]
    245 |   memset(this + 1, 0, DataSize);
        |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

To avoid this, we add an explicit type cast. The cast to void makes
sense, since other member functions of TypeSourceInfo also treat the
buffer `(this + 1)` of length `DataSize` as opaque memory, and was
likely left out by mistake.

Fixes: 4498663f3de0 ("[AST] Initialized data after TypeSourceInfo")