[libclang/python] Add missing concept declaration CursorKind (#69125)
Maps to
[`CXCursor_ConceptDecl`](https://github.com/llvm/llvm-project/blob/9b3d748c9ff5b5d9de448f071e2a0b5bea40b439/clang/include/clang-c/Index.h#L2716),
added in 9b3d748c9ff5b5d9de448f071e2a0b5bea40b439.

Without this I get this error on my codebase which uses C++20 concept
decls:
```
ValueError: Unknown template argument kind 604
```