[Support] FIx a warning
This patch fixes:

  llvm/include/llvm/Support/ErrorHandling.h:62:6: error: declaration
  is marked with '@deprecated' command but does not have a deprecation
  attribute [-Werror,-Wdocumentation-deprecated-sync]