[bazel][libc][NFC] Add missing layering deps (#107947)
After 6a371fd65cbf3c088e2738aa05b804975b45c15d

e.g.

```
external/llvm-project/libc/test/src/math/smoke/NextTowardTest.h:12:10: error: module llvm-project//libc/test/src/math/smoke:nexttowardf_test does not depend on a module exporting 'src/__support/CPP/bit.h'
```