Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit 0bac5a3162bd55cd2f47fe4637f9f356c876d985.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found