llvm-gsymutil now handles empty linkage names correctly.
Previous to this fix, if we had a DW_TAG_subprogram that had a DW_AT_linkage_name that was empty, it would attempt to use this name which would cause an error to be emitted when saving the gsym file to disk:

  error: DWARF conversion failed: : attempted to encode invalid FunctionInfo object

This patch fixes this issue and adds a unit test case.