Revert "Use-after-return sanitizer binary metadata"
This reverts commit fa55033789bae2771b50eea2eb1b367680eac746.

This patch results in:

  llvm/lib/CodeGen/SanitizerBinaryMetadata.cpp:57:17: error: no member
  named 'size' in 'llvm::MDTuple'