[windows] Don't allow env vars that differ only in LLVMConfig
For example, in LLDB shell tests, both `SystemRoot` and
`SYSTEMROOT` are forwarded to Swift, resulting in:
```
  # .---command stderr------------
  # | Swift/NativeDictionary.swift:823: Fatal error: Duplicate values for key: 'ProcessEnvironmentKey(value:
  "SYSTEMROOT")'
  # `-----------------------------
  # error: command failed with exit status: 0xc000001d
```

Per
https://github.com/swiftlang/swift/issues/84428#issuecomment-3320471717,
this is intended behavior.

This change adjusts `with_environment` to a "last wins" policy, removing
any existing keys that will clash with new keys.