[AArch64] Fix a warning
This patch fixes:

  llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:6102:9: error:
  unused variable 'OpVT' [-Werror,-Wunused-variable]