[lldb][minidump] Skip the new minidump tests on ARM (#214766)
Apparently, the new tests introduced by #212641 and #212861 use features
not supported on ARM.

Example:
```
FAIL: test_save_core_range_with_unreadable_tail_dwarf (TestProcessSaveCoreMinidumpPartialRead.ProcessSaveCoreMinidumpPartialReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../lldbtest.py", line 2171, in test_method
    return attrvalue(self)
  File ".../TestProcessSaveCoreMinidumpPartialRead.py", line 78, in test_save_core_range_with_unreadable_tail
    self.assertSuccess(process.SaveCore(options))
  File ".../lldbtest.py", line 3045, in assertSuccess
    self.fail(self._formatMessage(msg, "'{}' is not success".format(error)))
AssertionError: 'architecture arm not supported.' is not success
Config=arm-/home/tcwg-buildbot/worker/lldb-arm-ubuntu/build/bin/clang
```