[ORC] Fix compile error (#164411)
This fixes the following error we're getting internally, perhaps only
with the latest clang:

llvm/include/llvm/ExecutionEngine/Orc/WaitingOnGraph.h:136:24: error:
missing '#include <__fwd/vector.h>'; default argument of 'vector' must
be defined before it is used

This is a fix for #164340.