[Clang][Sema] Fix lambda attribute processing order with clang optimize off (#217194)
This PR fixes a regression from #215173 where an `always_inline` lambda
on a `#pragma clang optimize off` will throw a compiler error. For
example,

```
#pragma clang optimize off

// 1. function:
__attribute__((always_inline)) void front_func() {}

// 2. lambda:
auto trailing_lambda = []() __attribute__((always_inline)) { return 42; };
```

causes only an error for the lambda, not function:

```
/tmp/repro.cpp:7:44: error: 'always_inline' and '__noinline__' attributes are not compatible
    7 | auto trailing_lambda = []() __attribute__((always_inline)) { return 42; };
      |                                            ^
/tmp/repro.cpp:1:15: note: conflicting attribute is here
    1 | #pragma clang optimize off
      |               ^
1 error generated
```
This would fail loudly as d3d3d4d502fc8728ecccd1e1dc283af7dd52d5d4
enforces mutual exclusions between `always_inline` and `no_inline`.

The fix here is to ensure lambdas follow the same pattern as functions.
For functions, in `SemaDecl.cpp` we called `ProcessDeclAttributes()`
which adds `always_inline` before `AddRangeBasedOptNone()` (which guards
against adding `no_inline` if `always_inline` is already present).
Lambdas had the order reversed however, so this patch reorders these
correctly.