Revert "[clang] Implement Change scope of lambda trailing-return-type"
This reverts commit facb233005c98868943684fa545627d738333e99.
This broke clang bootstrap: it made existing C++ code in LLVM invalid:

llvm/include/llvm/CodeGen/LiveInterval.h:630:53: error: captured variable 'Idx' cannot appear here
              [=](std::remove_reference_t<decltype(*Idx)> V,
                                                    ^