Fix MSVC compile error in BitstreamRemarkParser.h when targeting C++17
The following errors are seen in our builds using MSVC 2022:

BitstreamRemarkParser.h(115): error C2990: 'llvm::remarks::BitstreamBlockParserHelper': non-class template has already been declared as a class template
BitstreamRemarkParser.h(66): note: see declaration of 'llvm::remarks::BitstreamBlockParserHelper'

This change fixes the build issue by adding an explicit template
argument to the `friend class` statements.

This issue is not seen if using `-std:c++20`, but we still support
building as C++17.