[bazel] Add missing deps for #141864 (#142437)
Added in bc6cb9f2c879480ac457d9ef95991dfc770093ed.

```
external/llvm-project/llvm/include/llvm/Frontend/Driver/CodeGenOptions.h:16:10: error: module llvm-project//llvm:FrontendDriver does not depend on a module exporting 'llvm/Support/Compiler.h'
#include "llvm/Support/Compiler.h"
```