evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit 18b39611cd97435f44efcefb5b74defb2e19f84b.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'