[libsycl] Fix debug build error caused by RTTI option mismatch
Fixes an undefined reference to typeinfo for `llvm::ErrorInfoBase`
during a debug build of libsycl.