[Flang][OpenMP]add semantic check for linear clause with statement function variables (#199743)
### **Description**

1. This patch adds a missing semantic check for the LINEAR clause.
2. OpenMP treats LINEAR variables similarly to PRIVATE variables.
Variables used inside statement function expressions are not allowed to
be privatized, but Flang was not checking this for LINEAR.
3. The existing privatization check already handled PRIVATE,
FIRSTPRIVATE, and LASTPRIVATE. This patch extends the same check to
LINEAR.

Fixes : [199660](https://github.com/llvm/llvm-project/issues/199660)

### **Reproducer**
```
subroutine test()
  integer :: pi, r, f, x
  f(r) = pi * r + x
  !$omp parallel do linear(x)
  do r = 1, 10
    pi = f(r)
  end do
  !$omp end parallel do
end subroutine
```
when compiled with : `-fopenmp -fopenmp-version=45 -c`

**Observed Behavior**

` No diagnostic emitted
`

**Expected Behavior**

```
error: Variable 'x' in statement function expression cannot be in a LINEAR clause
    !$omp parallel do linear(x)
```

Co-authored-by: Jay Satish Kumar Patel <kumarpat@pe31.hpc.amslabs.hpecorp.net>