[mlir][IR][NFC] Disambiguate `SymbolTable::Visibility` references
As a follow-up to 979b722, address MSVC's confusion when it's
trying to resolve the enum name:
```
error C2955: 'mlir::OpTrait::SymbolTable': use of class template requires template argument list
```

Assisted-by: OpenAI Codex
Signed-off-by: Artem Gindinson <gindinson@roofline.ai>