[bazel][mlir] Add missing dep and include after cdb5a7d0b0593bf5cfea369607181340f8a625ee
This fixes issues when compiling SliceMatchers.h separately. In
particular, the missing include triggered a "member access into
incomplete type" error:

```
third_party/llvm/llvm-project/mlir/include/mlir/Query/Matcher/SliceMatchers.h:91:30: error: member access into incomplete type 'Operation'
   91 |     for (auto operand : subOp->getOperands()) {
      |                              ^
third_party/llvm/llvm-project/mlir/include/mlir/Analysis/SliceAnalysis.h:20:7: note: forward declaration of 'mlir::Operation'
   20 | class Operation;
      |       ^
```