Remove unused variable 's32' in X86LegalizerInfo.cpp (NFC)
/data/llvm-project/llvm/lib/Target/X86/X86LegalizerInfo.cpp:470:13: error: unused variable 's32' [-Werror,-Wunused-variable]
  const LLT s32 = LLT::scalar(32);
            ^
1 error generated.