[SPIR-V] Add missing ScalarOpts library (#114384)
Fixes an "undefined reference to `llvm::createRegToMemWrapperPass()'"
linker error introduced by cba70550ccf5 ("[SPIR-V] Fix BB ordering &
register lifetime (#111026)", 2024-10-30).