[DebugInfo][RegisterCoalescer] Drop DBG_VALUEs with unsupported register class
During the inflation stage, some registers may be changed to a type that
is not supported by DBG_VALUE. It may happen because
MachineRegisterInfo::recomputeRegClass() doesn't take DBG_VALUEs into account.

MachineRegisterInfo::recomputeRegClass() was changed to compute
constraints for a set of all uses and a set of non-dbg uses.
If the computed classes don't match, it considers encountered DBG_VALUEs
as illegal and returns a list of them for further processing.

RegisterCoalescer marks such unsupported DBG_VALUEs as undefs.

The reason for this change is a crash I encountered while trying to
build compiler-rt builtins on macOS with CMAKE_BUILD_TYPE=RelWithDebInfo,
LLVM_TARGETS_TO_BUILD=all, LLVM_ENABLE_ASSERTIONS=On,
LLVM_ENABLE_EXPENSIVE_CHECKS=On.

Here's the error message:
```
*** Bad machine code: Invalid register class for subregister index ***
- function:    __addsf3
- basic block: %bb.29 if.then116.i (0x121015050) [4368B;4752B)
- instruction: DBG_VALUE %22.sub_8bit:gr32, $noreg, !"sticky", !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value), debug-location !261; llvm-project/compiler-rt/lib/builtins/fp_add_impl.inc:0 @[ llvm-project/compiler-rt/lib/builtins/addsf3.c:16:59 ] line no:136
- operand 0:   %22.sub_8bit:gr32
Register class GR32 does not fully support subreg index sub_8bit
fatal error: error in backend: Found 1 machine code errors.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /Users/vlad/Developer/llvm/llvm-build-native/bin/clang --target=arm64-apple-darwin24.5.0 -O2 -g -DNDEBUG -arch i386 -isysroot /Applications/Xcode-16.4.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -isysroot /Applications/Xcode-16.4.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -mmacosx-version-min=10.7 -fPIC -O3 -fvisibility=hidden -DVISIBILITY_HIDDEN -Wall -fomit-frame-pointer -DHAS_ASM_LSE -Werror=format-nonliteral -DDONT_DEFINE_EPRINTF -arch i386 -MD -MT CMakeFiles/clang_rt.builtins_i386_osx.dir/addsf3.c.o -MF CMakeFiles/clang_rt.builtins_i386_osx.dir/addsf3.c.o.d -o CMakeFiles/clang_rt.builtins_i386_osx.dir/addsf3.c.o -c /Users/vlad/Developer/llvm/llvm-project/compiler-rt/lib/builtins/addsf3.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/Users/vlad/Developer/llvm/llvm-project/compiler-rt/lib/builtins/addsf3.c'.
4.	Running pass 'Verify generated machine code' on function '@__addsf3'
 #0 0x00000001092c90d0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/vlad/Developer/llvm/llvm-build-native/bin/clang-21+0x104c990d0)
...
 #7 0x0000000109238b58 llvm::report_fatal_error(llvm::Twine const&, bool) (/Users/vlad/Developer/llvm/llvm-build-native/bin/clang-21+0x104c08b58)
 #8 0x000000010671082c llvm::initializeMachineVerifierLegacyPassPass(llvm::PassRegistry&) (/Users/vlad/Developer/llvm/llvm-build-native/bin/clang-21+0x1020e082c)
 #9 0x0000000106711708 (anonymous namespace)::MachineVerifierLegacyPass::runOnMachineFunction(llvm::MachineFunction&) (/Users/vlad/Developer/llvm/llvm-build-native/bin/clang-21+0x1020e1708)
 #10 0x0000000106650068 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/Users/vlad/Developer/llvm/llvm-build-native/bin/clang-21+0x102020068)
...
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 21.0.0git (git@github.com:llvm/llvm-project.git 351f15ba82f861cd7441f613db8317c353ca79c2)
Target: i386-apple-darwin24.5.0
Thread model: posix
InstalledDir: /Users/vlad/Developer/llvm/llvm-build-native/bin
Build config: +assertions, +expensive-checks
clang: note: diagnostic msg:
```

Full cmake config and build command:
```
cmake \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_INSTALL_PREFIX="native" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
  -DLLVM_CCACHE_BUILD=On \
  -DLLVM_ENABLE_ASSERTIONS=On \
  -DLLVM_ENABLE_BINDINGS=Off \
  -DLLVM_ENABLE_CURL=On \
  -DLLVM_ENABLE_PROJECTS="llvm;clang;lldb;lld;cross-project-tests" \
  -DLLVM_ENABLE_REVERSE_ITERATION=On \
  -DLLVM_TARGETS_TO_BUILD=all \
  -DLLVM_LIT_ARGS="-sv -j 10" \
  -DLLDB_ENABLE_PYTHON=On \
  -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;compiler-rt;libunwind" \
  -DLLVM_ENABLE_EXPENSIVE_CHECKS=On \
  -DDEFAULT_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)" \
  ../llvm-project/llvm
ninja runtimes/builtins-stamps/builtins-build
```