[lldb-instr] Pass PCHContainerOperations to ClangTool
On a local modules build this would cause an error.

> fatal error: no handler registered for module format 'obj'
> LLVM ERROR: unknown module format

Interestingly enough, this didn't trigger on the GreenDragon CMake bot,
which is configured with modules.

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@353869 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit f5a3562a60678e2222a12c193096047058626c72)

apple-llvm-split-commit: fa72070625155a58f0cb75483c9e93ccb89d37dc
apple-llvm-split-dir: lldb/