[libcxxabi] Don't enable -fvisibility=hidden on Windows
This option is supported (and hence gets added by the
target_add_compile_flags_if_supported function) on Windows, but
using hidden/default visibility should be mutually exclusive to
using dllexport vs no dllexport.

In asserts enabled builds of Clang, building with -fvisibility=hidden
caused errors like this:

    dllexport GlobalValue must have default or protected visibility
    ptr @_ZTIv
    [...]
    fatal error: error in backend: Broken module found, compilation aborted!

Since we're using dllexport on Windows to limit which symbols
get exported, don't try to use -fvisibility=hidden. (If we'd use
that option, we would also need to use per-symbol attributes to
mark symbols with default visibility for the symbols that we do
want exported.)

This fixes Windows builds with Clang with asserts enabled, after
cb942d009a5ed029ce20d9b75b3604f551f0cb56.