[MLIR] Use false instead of nullptr for boolean args. (NFC)
This fixes a build failure on macOS with -Werror:
  error: implicit conversion of nullptr constant to 'bool' [-Werror,-Wnull-conversion]