[mlir][gpu] Fix breaking constructor from GPUSubgroupSizeToROCDL
We are adding GPUSubgroupSizeToROCDL to patterns function that do not
have a valid constructor for it. This is causing said error below:

error: constructor inherited by 'GPUSubgroupSizeOpToROCDL'
from base class 'ConvertOpToLLVMPattern<mlir::gpu::SubgroupSizeOp>' is implicitly deleted

Signed-off-by: Stanley Winata <stanley.winata@amd.com>