[lldb] Unbreak debian build after dd76375c8009
From the lldb-x86_64-debian buildbot:
```
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/source/Plugins/SymbolFile/DWARF/DWARFUnit.cpp:984:16: error: call to deleted constructor of 'llvm::Error'
        return err;
               ^~~
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/llvm/include/llvm/Support/Error.h:189:3: note: 'Error' has been explicitly marked deleted here
  Error(const Error &Other) = delete;
  ^
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/llvm/include/llvm/Support/Error.h:496:18: note: passing argument to parameter 'Err' here
  Expected(Error Err)
                 ^
1 error generated.
```

(cherry picked from commit 91223c92f7f7e1a6c074a28de6b5206c22eec116)