[BoundsSafety] Fix `clang/test/BoundsSafety/CodeGen/unique-trap-blocks-O0-O2-opt-disabled.c`
The test failed because of upstream changes to TBAA

```
commit 458b1e9d2c61945f62b5bdfda93914d6a46b6cc7
error: cannot run gpg: No such file or directory
Author: Bruno De Fraine <brunodf@synopsys.com>
Date:   Thu Feb 20 13:06:56 2025 +0100

    [TBAA] Refine pointer-tbaa for void pointers by pointer depth (#126047)
```

rdar://145309621