[lldb][test][NFC] Remove BOM characters from tests
These handful of tests had a BOM (Byte order mark)
at the beginning of the file. This marker is unnecessary
in our test files. The main motivation for this is that
the `ast` python module breaks when passing a file to it
with a BOM marker (and might break other tooling which
doesn't expect it). E.g.,:
```
"""Test that lldb command 'process signal SIGUSR1' to send a signal to the inferior works."""
^
SyntaxError: invalid non-printable character U+FEFF
```

If anyone is aware of a good reason to keep it, happy
to drop this.