Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit 9230f0065a6f594a5b64c8199bf917af68820afc.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.