[mlir] Fix a warning
This patch fixes:

  mlir/lib/Transforms/Utils/DialectConversion.cpp:2761:9: error:
  unused variable 'impl' [-Werror,-Wunused-variable]