[lldb][test] PlatformDarwinTest: remove redundant usage of TestingProperties
This was failing to compile on Windows bots that built without assertions:
```
C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\lldb\unittests\Platform\PlatformDarwinTest.cpp
C:\Users\tcwg\llvm-worker\lldb-aarch64-windows\llvm-project\lldb\unittests\Platform\PlatformDarwinTest.cpp(554,3): error: use of undeclared identifier 'TestingProperties'
  554 |   TestingProperties::GetGlobalTestingProperties().AppendSafeAutoLoadPaths(
      |   ^
1 error generated.
```

We don't need to set the safe-paths in this particular test, so just remove it.