Revert "[lldb] Upstream support for Foundation constant classes"
This reverts commit da58d528d8a39a50d94a1ad12c4c42b73aeda528.

This breaks build bots witha  missing file:
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/source/Plugins/Language/ObjC/Cocoa.cpp:10:10: fatal error: 'objc/runtime.h' file not found