Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 64272005760bece7bf3dd7e347e9704eaa0a217f.

It again broke builds on Windows:

  lldb/source/Host/common/HostNativeThreadBase.cpp(37,14): error:
  assigning to 'lldb::thread_result_t' (aka 'unsigned int') from
  incompatible type 'std::nullptr_t'