[lldb] Use -Wno-documentation-deprecated-sync if available (#138909)
report_fatal_error has been marked "@deprecated" in its comment, but
the function itself is not marked with [[deprecated]] yet.  This
causes warnings like:

  llvm/include/llvm/Support/ErrorHandling.h:61:6: error: declaration
  is marked with '@deprecated' command but does not have a deprecation
  attribute [-Werror,-Wdocumentation-deprecated-sync]

  llvm/include/llvm/Support/Error.h:738:6: error: declaration is
  marked with '@deprecated' command but does not have a deprecation
  attribute [-Werror,-Wdocumentation-deprecated-sync]

This patch disables the warning while we migrate away from
report_fatal_error.