[lldb][test] Only set ASAN options in ASAN-builds
Without this the unit-tests currently fail with:
```
llvm-lit: /Volumes/SSD/Apple-internal/llvm-project/llvm/utils/lit/lit/TestingConfig.py:156: fatal: unable to parse config file '/Volumes/SSD/Apple-internal/llvm-project/lldb/test/Unit/lit.cfg.py', traceback: Traceback (most recent call last):
  File "/Volumes/SSD/Apple-internal/llvm-project/llvm/utils/lit/lit/TestingConfig.py", line 144, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SSD/Apple-internal/llvm-project/lldb/test/Unit/lit.cfg.py", line 47, in <module>
    config.environment['ASAN_OPTIONS'] += ':' + 'detect_container_overflow=0'
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'ASAN_OPTIONS'
```

I suspect this was an unfortunate consequence of https://github.com/llvm/llvm-project/commit/4d4024e1edf354113e8d0d11661d466ae5b0bee7 where the auto-merger kept the Swift-only block outside of the newly added if-block without conflict.

This change only exists on the `next` branches at the moment, which is probably why we didn't notice.