[MLIR/Utils] Add missing dep on Arith dialect
Fix the following compile error when building libMLIRDialectUtils.a
only:

In file included from mlir/include/mlir/Dialect/Utils/ReshapeOpsUtils.h:17,
                 from mlir/lib/Dialect/Utils/ReshapeOpsUtils.cpp:9:
mlir/include/mlir/Dialect/Arith/IR/Arith.h:28:10:
fatal error: mlir/Dialect/Arith/IR/ArithOpsDialect.h.inc: No such file or directory