[BoundsSafety] fix counted_by on ObjC methods in ObjC++ mode
ObjC method parsing diverges significantly from normal C function
parsing. This results in decl contexts for both parameters, as well as
the methods/functions themselves differing between the two. When parsing
a C function, the decl context of the parameters is the same as that of
the function, until parsing of the function body starts. This means that
they will be equal when late parsing bounds attributes. For ObjC
methods, the decl context for parameters is always the ObjCMethodDecl.
This deviation means that tryCaptureVariable() will do its full analysis
when parsing count expressions on ObjC methods. In ObjC mode this
doesn't pose an issue, but in ObjC++ mode this results in emitting
the following diagnostic for every referenced parameter:
```
error: reference to local variable 'len' declared in enclosing context
```

By temporarily entering the context of the ObjCMethodDecl while parsing
the bounds attributes, the `VarDC == CurContext` check passes and
tryCaptureVariable() does an early exit. Normally ParseLexedCAttribute()
will enter the function context for C/C++ functions and methods, but
those LateParsedAttributes are attached to the function/method, whereas
they are attached to the parameters for ObjC methods. The current scope
also already contains the ObjC parameters, so we don't need to do a
normal full method scope entering; instead we only set CurContext. For
this reason the context is entered before calling
ParseLexedCAttributeList.

rdar://168702220