Fix assertion build failure (#27)
```
llvm-project/llvm/include/llvm/Support/Casting.h:549:46:   required from ‘bool llvm::isa(const From&) [with To = mlir::GENX::JointMatrixType; From = llvm::Type*]’
llvm-project/mlir/lib/Target/LLVMIR/Dialect/GENX/GENXToLLVMIRTranslation.cpp:239:3:   required from here
llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:111:54: error: static assertion failed: casting from a non-convertible type
  111 |     static_assert(std::is_convertible<ConcreteT, T>::value,
      |                                                      ^~~~~
llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:111:54: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:113:16: error: request for member ‘getTypeID’ in ‘val’, which is of pointer type ‘const llvm::Type*’ (maybe you meant to use ‘->’ ?)
  113 |     return val.getTypeID() == getTypeID();
```

---------

Signed-off-by: Whitney Tsang <whitney.tsang@intel.com>