[CIR] Add custom assembly format for alloca op to fix flag parsing (#198962)
The previously used assembly format was generating code like:
```cpp
  if (::mlir::succeeded(parser.parseOptionalComma())) {
    props.init = parser.getBuilder().getUnitAttr();
    if (parser.parseKeyword("init"))
      return ::mlir::failure();
  }
```
This means that upon seeing any comma, the parser would immediately set
the `init` attribute and then expect the keyword "init" to follow. So a
valid input like `["n", const]` would fail with:
```bash
  error: expected 'init'
```