[libunwind] Fix return type of DwarfFDECache::findFDE() in definition
Needed to resolve this compilation error on some systems:

        lib/libunwind/src/UnwindCursor.hpp:153:38: error: return type of out-of-line definition of 'libunwind::DwarfFDECache::findFDE' differs from that in the declaration
    typename A::pint_t DwarfFDECache<A>::findFDE(pint_t mh, pint_t pc) {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        lib/libunwind/src/libunwind.cpp:31:10: note: in file included from lib/libunwind/src/libunwind.cpp:31:
    #include "UnwindCursor.hpp"
             ^
        lib/libunwind/src/UnwindCursor.hpp:100:17: note: previous declaration is here
      static pint_t findFDE(pint_t mh, pint_t pc);
             ~~~~~~~^