[sanitizer_common][test] Move fork_threaded.c to Linux
Since the new `Posix/fork_threaded.c` test was enabled for `ubsan`, the
test `FAIL`s on Solaris (and most likely all other non-Linux targets):

```
FAIL: SanitizerCommon-ubsan-sparc-SunOS::fork_threaded.cpp
FAIL: SanitizerCommon-ubsan-sparcv9-SunOS::fork_threaded.cpp

/opt/llvm-buildbot/home/solaris11-sparcv9/clang-solaris11-sparcv9/llvm/compiler-rt/test/sanitizer_common/TestCases/Posix/fork_threaded.cpp:79:33: error: use of undeclared identifier '__WALL'; did you mean 'P_ALL'?
   79 |     while (waitpid(-1, &status, __WALL) != pid) {
      |                                 ^~~~~~
      |                                 P_ALL
/usr/include/sys/procset.h:45:2: note: 'P_ALL' declared here
   45 |         P_ALL,          /* all processes                                */
      |         ^
```
The use of `__WALL` is unportable, AFAICS it's a glibc addition, certainly
not POXIX.

This patch moves the test to `Linux` to match this.

Tested on `x86_64-pc-linux-gnu` and `amd64-pc-solaris2.11`.