Revert "[ADT] Support const-qualified unique_functions"
This reverts commit 15fccdc815e047cd53571088cef647b4a1c6c09b.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;