Revert "Reland "[Clang] Enable -Wunused-template under -Wall" (#208001)"
[hipDNN] /__w/llvm-project/llvm-project/rocm-libraries/projects/hipdnn/data_sdk/include/hipdnn_data_sdk/utilities/ShapeUtilities.hpp:348:13:
 error: unused function template 'iterateAlongDimensions' [-Werror,-Wunused-template]

This reverts commit 1529d35adbd6f13aa234a5f4cfd9ac0e28bdd338.