[libc++] Use .set for symbol assignment on Hexagon
std::__is_function_overridden() defines __impl_ref<_Func>::__impl_ as a local
uses asm (`sym = expr`). On Hexagon `=` is the operand assignment
operator of the instruction syntax, so the assembler parses that line as an
instruction and rejects it:

  overridable_function.h:106:11: error: unrecognized instruction
    106 |   __asm__("%cc0 = %cc1" : : "X"(...), "X"(_Func));
        |           ^
  <inline asm>:1:2: note: instantiated into assembly here
      1 |         _ZNSt3__110__impl_refIXadL_ZnwjEEE7__impl_Ej = _Znwj

The assembler does accept the similar `.set sym, expr` directive, so
let's use that here.

This was encountered in libfuzzer's libc++ - built w/-fno-exceptions.