[crashlog] Print the actual exception in the CommandReturnObject
Before:

  error: python exception <class 'AttributeError'>

After:

  error: python exception: 'DarwinImage' object has no attribute 'debugger'

(cherry picked from commit f0fd4349a78aff99b7e2214bf1ffe9e352201de3)