Revert "Remove redundant "std::move"s in return statements"
The build failed with

  error: call to deleted constructor of 'llvm::Error'

errors.

This reverts commit ca63b11ae517dd513216101167e5e3e5c54db01f.