[libcxx] Bump __libcpp_version to 14 after branch
This was missed in fc3c342590dd467307474104f7dc9904f37354df
and caused test failures in the buildkite bots:
libcpp_version.pass.cpp:22:1:
error: static_assert failed due to requirement '14000 == libcpp_version'
"_LIBCPP_VERSION doesn't match __libcpp_version