[mlir] Fix a warning
This patch fixes:

  mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp:1544:14: error:
  unused variable 'destType' [-Werror,-Wunused-variable]