[flang] Fix POSIX.1/XPG checks in intrinsics-library.cpp
PR #201063 breaks the `flang` build on Solaris:

```
flang/lib/Evaluate/intrinsics-library.cpp:225:26: error: address of overloaded function 'acos' does not match required type '__float128 (__float128)'
flang/lib/Evaluate/intrinsics-library.cpp:225:26: error: address of overloaded function 'acos' does not match required type '_Complex __float128 (_Complex __float128)'

```

The problem is that the `__float128` support in `intrinsics-library.cpp` is
guarded incorrectly: it tests for `_POSIX_C_SOURCE >= 200112L` or
`_XOPEN_SOURCE >= 600`, which are no longer defined on Solaris after the PR
above.  This check is due a misunderstanding of those feature test macros:
as detailed in [The Open Group Base Specifications Issue 8, 2.2.1 POSIX.1
Symbols](https://pubs.opengroup.org/onlinepubs/9799919799/functions/V2_chap02.html),
those macros are expected to be **defined** by the user to ensure that the
features introduced by a particular version of POSIX.1 or XPG are enabled.
To test if they actually are supported, the values of `_POSIX_VERSION` or
`_XOPEN_VERSION` need to be checked instead, as explained in [2.1.3.1 POSIX
System
Interfaces](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap02.html).

If the XPG6 features required for `flang` are present by default in a
compilation environment, `_POSIX_VERSION` or `_XOPEN_VERSION` will be
defined to the required values even without defining `_POSIX_C_SOURCE` or
`_XOPEN_SOURCE`.

Tested on `amd64-pc-solaris2.11`, `sparcv9-sun-solaris2.11`, and
`x86_64-pc-linux-gnu`.