[PowerPC] Fix a warning
This patch fixes:

  llvm/lib/Target/PowerPC/PPCSelectionDAGInfo.h:25:3: error:
  'EmitTargetCodeForMemcmp' overrides a member function but is not
  marked 'override' [-Werror,-Winconsistent-missing-override]