Revert "[lsan] On Fuchsia, don't use atexit hook for leak checks"
This reverts commit a8d9f651dfcbdf2088ab403ecb5927a1eef2b29a.
This reverts commit 2306dfbacb4da824bfe9b07a6ff5ea83eafd7942.

Causes linker errors which were not fixed by the subsequent commit
either:

/home/nikic/llvm-project/compiler-rt/lib/asan/asan_rtl.cpp:503: error: undefined reference to '__asan::InstallAtExitCheckLeaks()'