fix pp-trace crashes with no options
Currently, executing pp-trace without parameters causes a crash.
Now:
```
# pp-trace
error: pp-trace: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: pp-trace --help
```