[analyzer][scan-build-py] Fix windows compatibility
It fails on windows 10 otherwise with:
```
Traceback (most recent call last):
 ...
  File "C:\Dev\LLVM\lib\libscanbuild\analyze.py", line 567, in
report_failure
    handle.write(" ".join(os.uname()) + os.linesep)
                          ^^^^^^^^
AttributeError: module 'os' has no attribute 'uname'. Did you mean:
'name'?
```

There was also a problem identifying the actual compiler on Windows
because the program name have an ".exe" suffix.