[flang] Fix an unused variable warning
This patch fixes:

  flang/lib/Semantics/runtime-type-info.cpp:1275:12: error: unused
  variable 'name' [-Werror,-Wunused-variable]