Revert "[flang] Enumeration Type: (PR 1/5) Foundation types + Parser" (#202408)
Reverts llvm/llvm-project#192651

It seems to be causing linker errors. Verified locally that reverting
this commit helps.
```
/usr/bin/ld: tools/flang/lib/Evaluate/CMakeFiles/FortranEvaluate.dir/type.cpp.o: in function `Fortran::evaluate::DynamicType::GetAlignment(Fortran::evaluate::TargetCharacteristics const&) const':
type.cpp:(.text._ZNK7Fortran8evaluate11DynamicType12GetAlignmentERKNS0_21TargetCharacteristicsE+0x71): undefined reference to `Fortran::semantics::DerivedTypeSpec::GetScope() const'
/usr/bin/ld: type.cpp:(.text._ZNK7Fortran8evaluate11DynamicType12GetAlignmentERKNS0_21TargetCharacteristicsE+0x87): undefined reference to `Fortran::semantics::DerivedTypeSpec::GetScope() const'
/usr/bin/ld: tools/flang/lib/Evaluate/CMakeFiles/FortranEvaluate.dir/type.cpp.o: in function `Fortran::evaluate::DynamicType::MeasureSizeInBytes(Fortran::evaluate::FoldingContext&, bool, std::optional<long>) const':
type.cpp:(.text._ZNK7Fortran8evaluate11DynamicType18MeasureSizeInBytesERNS0_14FoldingContextEbSt8optionalIlE+0x1ed): undefined reference to `Fortran::semantics::DerivedTypeSpec::GetScope() const'
/usr/bin/ld: type.cpp:(.text._ZNK7Fortran8evaluate11DynamicType18MeasureSizeInBytesERNS0_14FoldingContextEbSt8optionalIlE+0x202): undefined reference to `Fortran::semantics::DerivedTypeSpec::GetScope() const'
/usr/bin/ld: type.cpp:(.text._ZNK7Fortran8evaluate11DynamicType18MeasureSizeInBytesERNS0_14FoldingContextEbSt8optionalIlE+0x218): undefined reference to `Fortran::semantics::DerivedTypeSpec::GetScope() const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```