[flang] Do not invoke undefined behaviour when parsing format expressions
The test flang/test/Semantics/io08.f90 was failing when UBSAN was enabled:
/home/david.spickett/llvm-project/flang/include/flang/Common/format.h:224:26: runtime error: signed integer overflow: 10 * 987654321098765432 cannot be represented in type 'int64_t' (aka 'long')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/david.spickett/llvm-project/flang/include/flang/Common/format.h:224:26
error: Semantic errors in /home/david.spickett/llvm-project/flang/test/Semantics/io08.f90
/home/david.spickett/llvm-project/flang/test/Semantics/io08.f90:2:14: error: Integer overflow in format expression
    write(*,'(I98765432109876543210)')
               ^^^^^^^^^^^^^^^^^^^^

This is because the code was effectively:
* Take the risk of UB happening
* Check whether it happened or not

Which UBSAN is obviously not going to like. Instead of checking after the
fact, use llvm's helpers that catch overflow without actually doing it.