Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit bfe808398bdd7d6fea04eb55563ef6f6b2d16060. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```