Revert "[lineeditor] Add `setHistorySize()` method for adjusting history size (#110092)"
This reverts commit 7fdd49e81d25d9adf84595a3a2db94d8839165eb.

Reason: buildbot breakage (https://lab.llvm.org/buildbot/#/builders/66/builds/5904)

/home/b/sanitizer-x86_64-linux/build/llvm-project/llvm/lib/LineEditor/LineEditor.cpp:23:15: error: unused variable 'DefaultHistorySize' [-Werror,-Wunused-const-variable]
   23 | constexpr int DefaultHistorySize = 800;
      |               ^~~~~~~~~~~~~~~~~~
1 error generated.