Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit c23f9e91e74ebec21ac77e433de22b536e3d2395 because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }