[lldb] Fix compile error due implicit StringRef -> std::string conversion
This was failing with:
```
lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp:1276:24: error: no viable overloaded '='
  module->APINotesFile = apinotes;
  ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~
include/c++/v1/string:877:19: note: candidate function not viable: no known conversion from 'llvm::StringRef' to 'const std::__1::basic_string<char>' for 1st argument
    basic_string& operator=(const basic_string& __str);
                  ^
```

(cherry picked from commit 5206ce51aa2491020db27106048ecf352305d775)