[Flang][HLFIR] Bail out of EOSHIFT simplification for polymorphic arrays (#223118)
Consider the following code
```
module m
    type Base
        integer :: i = 8
    end type

    type, extends(Base) :: Child
        integer :: j = 9
    end type
end module

program argumentKeyword002
use m
    class(*), pointer :: b1(:,:,:), boundVal

    allocate(b1(3,2,2), SOURCE=reshape((/(i,i=1,12)/), &
     (/3,2,2/)))

    allocate (boundVal, source=0)

    select type(name1=>eoshift(SHIFT=reshape((/1,-2,2,-1/),(/2,2/)), &
     ARRAY=b1,DIM=1, BOUNDARY=boundVal))
        type is (integer)
            print *, name1
            print *, shape(name1)
        class default
            ERROR STOP(1_4)
    end select
end
```

it passed at `-O0` but failed at `-O3` as
```
argumentKeyword002.f":38:5): error: 'fir.result' op types mismatch between result op and its parent
error: Lowering to LLVM IR failed
```

The reason is that the `SimplifyHLFIRIntrinsics` is trying to inline
`EOSHIFT` of a `CLASS(*)` array as an `hlfir.elemental` produces a
`fir.if` with mismatched types on the branches (e.g., `!fir.class<none>`
vs. pointer-qualified `!fir.class<!fir.ptr<none>>`).

By looking at the code, we currently bail-out derived type array so it
falls back to the runtime code. Polymorphic array should be bailed-out
also for now and handled with derived type together in the future.