[sanitizer_common] Remove <procfs.h> workaround on Solaris
`sanitizer_procmaps_solaris.cpp` currently uses `#undef _FILE_OFFSET_BITS`
to hack around the fact that old versions of Solaris `<procfs.h>` don't
work in a largefile environment:

```
/usr/include/sys/procfs.h:42:2: error: #error "Cannot use procfs in the large file compilation environment"
   42 | #error  "Cannot use procfs in the large file compilation environment"
      |  ^~~~~
```

However, this is no longer an issue on either Solaris 11.4 or Illumos.  The
workaround only existed for the benefit of Solaris 11.3.  While that had
never been supported by LLVM, the sanitizer runtime libs were imported into
GCC's `libsanitzer`.  With the removal of Solaris 11.3 support in GCC 15,
this is no longer an issue and the workaround can be removed.

Tested on `amd64-pc-solaris2.11` and `sparcv9-sun-solaris2.11`.