[BoundsSafety][NFC] Revert "Revert "Fix bounds safty tests.""
This reverts commit 07f057b10a51976b5aa3edfa921ceec7e304cbbd.

In upstream this landed

```
commit e56a6a2683a82b21d47a5b881fb4eb104c5d8e0a
error: cannot run gpg: No such file or directory
Author: Nikita Popov <npopov@redhat.com>
Date:   Thu Feb 27 09:38:29 2025 +0100

    Reapply [CaptureTracking][FunctionAttrs] Add support for CaptureInfo (#125880) (#128020)
```

which is another attempt at landing #125880.

The `-fbounds-safety` tests were already adjusted when this was landed
before but we had to revert these changes when upstream reverted $125880.

So now this PR reverts the revert of the test changes.

Hopefully the upstream PR doesn't get reverted again.

rdar://145796299