[NFC][ClangOffloadWrapper] Add missing library
Otherwise, with BUILD_SHARED_LIBS=ON we get:

    /usr/bin/ld: tools/clang/tools/clang-offload-wrapper/CMakeFiles/clang-offload-wrapper.dir/ClangOffloadWrapper.cpp.o:
    undefined reference to symbol '_ZN4llvm10offloading18wrapOpenMPBinariesERNS_6ModuleENS_8ArrayRefINS3_IcEEEESt4pairIPNS_14GlobalVariableES8_ENS_9StringRefEb'