Revert "[Flang][OpenMP][Sema] Add OpenMP warning when mapping local descriptors to device on enter without a corresponding exit" (#203324)
Reverts llvm/llvm-project#201060

Warning is actually reporting an error causing compilation to fail:
error: Semantic errors in OpenMPTargetStream.F90

Above error from Babelstream. Can be seen with either of the following
reproducers:
aomp/test/smoke-fort/milestone-3-babel-copy
aomp/test/smoke-fort-dev/milestone-3-babel