[mlir][NFC] Remove unused variable 'indexType' in GPUTransformOps.cpp
/data/jiefu/llvm-project/mlir/lib/Dialect/GPU/TransformOps/GPUTransformOps.cpp:430:13: error: unused variable 'indexType' [-Werror,-Wunused-variable]
  IndexType indexType = rewriter.getIndexType();
            ^
1 error generated.