[libc] remove stdc_leading_zeros for now
The type generic macro had numerous issues.

The include test is broken for GCC.

    libc/test/include/stdbit_test.cpp:34:13: error: ‘_Generic’ was not declared in this scope
       34 |   EXPECT_EQ(stdc_leading_zeros(0ULL), static_cast<unsigned long long>(0xAF));
          |             ^~~~~~~~~~~~~~~~~~

Also, -Wc11-extensions (and thus -Wno-c11-extensions) are clang-only.

    cc1plus: note: unrecognized command-line option ‘-Wno-c11-extensions’ may
    have been intended to silence earlier diagnostics

And the hermetic test seems to be getting our generated stdbit.h, but the unit
tests does not.

I'll investigate this more later, but let's get the build bots back to green.