[llvm] Add missing dependency of libLLVMCodeGen on vt_gen
```
llvm-project/llvm/include/llvm/CodeGenTypes/MachineValueType.h:43:10: fatal error: 'llvm/CodeGen/GenVT.inc' file not found
   43 | #include "llvm/CodeGen/GenVT.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
```

rdar://141643651