Fix ExecuteAndWait with empty environment on Windows
CreateProcessW requires that the environemnt block to be always double
null-terminated even with an empty environemnt.

https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables

The attached test fails this way without the fix.

C:\Users\hiroshi\upstream\llvm-project\llvm\unittests\Support\ProgramTest.cpp(697): error: Value of: ExecutionFailed
  Actual: true
  Expected: false
  Couldn't execute program 'C:\Users\hiroshi\upstream\llvm-project\build\unittests\Support\SupportTests.exe': The parameter is incorrect.  (0x57)