Revert "Threading: Convert Optional to std::optional"
This reverts commit b0b5c86c55c06a5083500da167ab0a46771ed71c.

This commit breaks the build for BOLT:
  bolt/lib/Profile/DataAggregator.cpp:264:66: error: no viable
  conversion from 'Optional<StringRef>[3]' to
  'ArrayRef<std::optional<StringRef>>'