[flang][acc] Add missing dependencies for TestOpenACCSupport
Adds missing dependencies to avoid:
undefined reference to `mlir::acc::getOrCreateGPUModule`
undefined reference to `mlir::acc::OpenACCSupport::getVariableName`
after https://github.com/llvm/llvm-project/pull/222815