[libc] Fix LLVM_LIBC_FUNCTION on 32-bit x86 Windows
Previously, trying to compile libm with LIBC_COPT_PUBLIC_PACKAGING
defined failed on 32-bit Windows with

    error: alias must point to a defined variable or function

This is because 32-bit Windows adds a leading underscore to __cdecl
C functions, making the alias declaration not find its target symbol
name. The same problem exists on Apple platforms, which as solution
don't emit the alias for the C++ LIBC_NAMESPACE:: symbol.

Do the same on 32-bit Windows as on Apple platforms: Emit only
the underscore-prefixed symbol, not the LIBC_NAMESPACE:: alias.