[mlir][tosa] Handle unsigned constants in `TosaConvertIntegerTypeToSignless`
This commit fixes handling of unsigned constant data in the
`TosaConvertIntegerTypeToSignless` pass. Previoulsy, the type of the
"values" attribute would remain unsigned, which caused an error in
the const ops verifier:
```
error: 'tosa.const' op expected same attr/result element types
  %input_zp = "tosa.const"() {values = dense<17> : tensor<1xui8>} : () -> tensor<1xui8>
              ^
note: see current operation: %0 = "tosa.const"() <{values = dense<17> : tensor<1xui8>}> : () -> tensor<1xi8>
```
Now the constant data in "values" is transformed to signless as well.

Change-Id: I49f492ca1643a37885b5f44fc11f7614a6e158a3