[mlir] Fix a warning
This patch fixes:

  mlir/lib/Conversion/AMDGPUToROCDL/AMDGPUToROCDL.cpp:2666:10: error:
  unused variable 'v4i32' [-Werror,-Wunused-variable]