Revert "[lldb] [gdb-remote client] Refactor handling qSupported"
This reverts commit aaf4cddeb0198dd573f297e6ab5969ba8d24d052.

It fails to build, with errors such as:
  GDBRemoteCommunicationClient.cpp:1005:20:
  error: no viable overloaded '='
          avail_name = compression;