[LoongArch] Fix a warning
This patch fixes:

  llvm/lib/Target/LoongArch/LoongArchISelLowering.cpp:5354:7: error:
  unused variable 'VT' [-Werror,-Wunused-variable]