Revert "[lld-macho] Avoid using bump-alloc in TrieBuider"
This reverts commit cf1c4f4128fbfd0381d7a04d8af183b6a3db5e91.

That commit breaks the build with errors of the form:

/usr/local/google/home/saugustine/llvm/llvm-project/lld/MachO/ExportTrie.cpp:148:11: error: definition of implicitly declared destructor
TrieNode::~TrieNode() {