Revert "Fix amdgpu-arch for dll name on Windows (#101350)"
This reverts commit c4a6b8f89db18b5f0511e1f8bcb35204a991b006.

Revert it due to breaking buildbot:

Z:\b\llvm-clang-x86_64-sie-win\llvm-project\clang\tools\amdgpu-arch\AMDGPUArchByHIP.cpp(104):
 error C2039: 'parse': is not a member of 'llvm::VersionTuple'

https://lab.llvm.org/buildbot/#/builders/46/builds/13184