[libcxx] fix missing __get_locale_encoding() for OpenBSD
Fixes errors like this:

    /home/alexrp/Sources/ziglang/zig-llvm23/lib/libcxx/src/text_encoding.cpp:34:43: error: no member named '__get_locale_encoding' in namespace
        'std::__locale'
    34 |     return __make_text_encoding(__locale::__get_locale_encoding(static_cast<__locale::__locale_t>(0)));
        |                                           ^~~~~~~~~~~~~~~~~~~~~
    /home/alexrp/Sources/ziglang/zig-llvm23/lib/libcxx/src/text_encoding.cpp:48:41: error: no member named '__get_locale_encoding' in namespace
        'std::__locale'
    48 |   return __make_text_encoding(__locale::__get_locale_encoding(__l));
        |                                         ^~~~~~~~~~~~~~~~~~~~~
    2 errors generated.