Revert D137868 "[libc] Fix builtin definition for memory functions"
This reverts commit 28389fd1cc0929aad601b8ab716dd0a8055226d9.

This caused -Wmacro-redefined
```
.../libc/src/string/memory_utils/op_x86.h:31:9: error: '_mm512_cmpneq_epi8_mask' macro redefined [-Werror,-Wmacro-redefined]
        ^
.../lib/clang/google3-trunk/include/avx512bwintrin.h:294:9: note: previous definition is here
        ^
```