[OCaml] Try to fix library dependencies
Whenever I try to change anything in the OCaml bindings, I run into
errors like this when running tests:

    File "/home/npopov/repos/llvm-project/build/test/Bindings/OCaml/Output/debuginfo.ml.tmp/Testsuite.ml", line 1:
    Warning 70 [missing-mli]: Cannot find interface file.

    File "/home/npopov/repos/llvm-project/build/test/Bindings/OCaml/Output/debuginfo.ml.tmp/debuginfo.ml", line 1:
    Error: The files "/home/npopov/repos/llvm-project/build/lib/ocaml/llvm/llvm.cmi"
           and "/home/npopov/repos/llvm-project/build/lib/ocaml/llvm/llvm_debuginfo.cmi"
           make inconsistent assumptions over interface "Llvm"

The only reliable way of getting rid of these I have found is to
do an `rm -rf build` and just rebuild everything.

This PR tries to fix this issue by adding an additional dependency
on the `.cmi` files of dependent modules.

Disclaimer: This solution was suggested by Claude Code, so I'd
appreciate a careful look from someone who understands all these
different ocaml files.