[Comgr] Add missing clangOptions
Fixes error:

  /usr/bin/ld:
  tools/comgr/CMakeFiles/amd_comgr.dir/src/comgr-compiler.cpp.o: in
  function
  `COMGR::AMDGPUCompiler::executeInProcessDriver(llvm::ArrayRef<char
  const*>)':
  amd/comgr/src/comgr-compiler.cpp:739:
  undefined reference to `clang::getDriverOptTable()'
  collect2: error: ld returned 1 exit status
  ninja: build stopped: subcommand failed.