[flang] CYGWIN required _GNU_SOURCE to be defined.
Compiling flang on CYGWIN prints this error message on the console:

llvm-project/flang/include/flang/Parser/char-block.h: In member function ‘std::string Fortran::parser::CharBlock::NULTerminatedToString() const’:
llvm-project/flang/include/flang/Parser/char-block.h:106:26: error: ‘strnlen’ was not declared in this scope; did you mean ‘strlen’?
  106 |         /*not in std::*/ strnlen(interval_.start(), interval_.size())};
      |                          ^~~~~~~
      |                          strlen

strnlen() exists into NEWLIB, but it requires to define _GNU_SOURCE macro somewhere for having its prototype available.
This patch adds this definition, by using the same code written here:

https://github.com/llvm/llvm-project/blob/53602e6193d98b1e814b76a27e99ef7e18c9769c/third-party/benchmark/CMakeLists.txt#L230