[lldb] Keep the inferior's terminal open until LLDB read its output (#229387)
lldb gives the inferior the secondary side of a pseudo terminal for its
stdio and drains the primary side (what we get back from from
posix_openpt) via ThreadedCommunication's read thread.

On Darwin, it seems that closing the last secondary descriptor clears
the terminal's contents. Any output the inferior wrote but that the read
thread has not consumed yet is then destroyed alongside the inferior.

There isn't really any guarantee that we read the inferior's output
before it dies (and closes its secondary side of the terminal). So
reading stdout is currently racy in LLDB. This is also why
TestTargetAPI.py randomly fails to read the output:

```
  File ".../lldb/test/API/python_api/target/TestTargetAPI.py", line 189
    self.assertIn("arg: foo", output)
  AssertionError: 'arg: foo' not found in ''
```

The easiest way to make this race more likely is to sleep at the start
of ThreadedCommunication::ReadThread's main loop like this:

```
static std::chrono::milliseconds g_stdio_read_delay(800);

// in ThreadedCommunication::ReadThrea
  while (!done && m_read_thread_enabled) {
    // sleep if we're the stdio reader thread.
    if (GetBroadcasterName() == "process.stdio")
      std::this_thread::sleep_for(g_stdio_read_delay);
```

This patch fixes this by also making LLDB open the secondary side of the
terminal so that the the pty outlives the inferior. Then, LLDB can read
all stdout contents and close the secondary (and the pty).

assisted-by: claude