Revert "Fix attr docs from previous no-unique-adderss change (#67195)"
This reverts commit 44f2db7493454b41d2f5c81b76bd30f2f035ed31.

It caused
```
error: Record `NoUniqueAddress', field `Documentation' exists but does not have a list value
```