Revert "[lld-macho] Fix symbol relocs handling for compact unwind's functionAddress"
This reverts commit bddd72ff172d901f4aa76c59731b5650f289246e.

The commit in question causes:

  lld/MachO/InputFiles.cpp:916:13: error: use of undeclared identifier
  'it'