[BoundsSafety] Unbreak several codegen tests
This commit (and its corresponding merge commit) broke several codegen
tests.

```
commit 4b59b95733c1e89755f3f92272bc662e0db68712
Merge: c5ca74521067 c37b2549ff01
Author: git apple-llvm automerger <am@git-apple-llvm>
Date:   Fri May 2 23:22:29 2025 -0700

    Merge commit 'c37b2549ff01' from llvm.org/main into next

commit c37b2549ff0150301eb23bd28c2802efc426b7f2
error: cannot run gpg: No such file or directory
Author: Yingwei Zheng <dtcxzyw2333@gmail.com>
Date:   Fri May 2 05:21:59 2025 +0800

    Revert "[InstSimplify] Fold getelementptr inbounds null, idx -> null (#130742)" (#138168)

    Revert #130742 for now to avoid breaking glibc failures until the
    workaround patches are landed.
```

This commit re-generates the failing codegen tests.

rdar://150697626