[MC] eatToEndOfStatement: eat trailing EOL with Lex()
eatToEndOfStatement() advances the lexer with Lexer.Lex(), which neither
filters comment tokens nor pops the include stack at Eof. It therefore
leaves the token after the newline unfiltered, and leads to a spurious
error:

```
.extern foo
/* comment */
nop

error: unexpected token at start of statement
```

Fix with Lex(). Loosely take and clean up tests from #218456