[NFC] Fix darwin failures due to missing headers (#179989)
Handle the include similar to ProgramTest, to fix the build failures in
darwin
```

/Users/buildbot/buildbot-root/aarch64-darwin/llvm-project/llvm/unittests/CAS/OnDiskCASLoggerTest.cpp:38:15: error: use of undeclared identifier '_NSGetEnviron'
      return *_NSGetEnviron();
              ^
1 error generated.

```