[semantics][acc] start handling clauses that use sections and components (#211606)
## Motivation
The current implementation of checking OpenACC data sharing clauses and
references is rather adhoc because the machinery could was only designed
to keep track of a single identifier. Sections currently track the base
object to which the refer while component reference throw away their
declared object. Duplicate / contradictory clause checking also has
similar issues. For example:

```fortran
subroutine outside_copied_section()
  implicit none
  real :: a(3)
  !$acc parallel default(none) copy(a(1:2))
    a(2) = -1.0
    a(3) = 1.0
    a(1) = a(2) + a(3)
  !$acc end parallel
end subroutine
subroutine wrong_copied_component()
  implicit none
  type :: t
    integer :: x
    integer :: y
  end type
  type(t) :: a
  integer :: s
  !$acc parallel default(none) copy(a%x, s)
    a%x = 1
    a%y = 2
    s = a%x + a%y
  !$acc end parallel
end subroutine
```

before this PR:
```
$ flang -fc1 -fopenacc example.f90
error: Semantic errors in /home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:29:5: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      a%x = 1
      ^
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:30:5: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      a%y = 2
      ^
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:31:9: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      s = a%x + a%y
          ^
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:31:15: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      s = a%x + a%y
```

## Purpose
This PR adds machinery to start reasoning about designators in clauses
in a more principled fashion and makes some roads into cleaning up the
checking for both whether a reference is contained by some clause in the
current scope and whether or not clauses overlap.

after this PR:

```
$ flang -fc1 -fopenacc example.f90
error: Semantic errors in /home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:8:5: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      a(3) = 1.0
      ^
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:9:19: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      a(1) = a(2) + a(3)
                    ^
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:30:5: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      a%y = 2
      ^
/home/akuhlenschmi/work/tmp/openacc-simple-default-none-repros.f90:31:15: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-mapping clause
      s = a%x + a%y
```

Keeping track of the full designator that was used in the clause list
requires comparison of designators, but designators are suffix-first
structures which leads to an awkward formulation of comparison. This PR
adds some abstraction (`DesignatorPath`) for reasoning about designator
containment.