Fix compilation with GCC 15.1.1
Missing standard includes cause compilation to fail with recent
compilers.

  In file included from llvm/lib/Support/ErrorHandling.cpp:16: llvm/include/llvm/ADT/SmallVector.h:88:69: error: ‘uint64_t’ was not declared in this scope
     88 |     typename std::conditional<sizeof(T) < 4 && sizeof(void *) >= 8, uint64_t,