[ADT] Add back ability to compare StringSet
StringSet comparison was broken after moving from llvm::Optional to std::optional because std::nullopt_t is not equality-comparable.
Without this patch a try to compare objects of StringSet type leads to compilation error:
```
llvm-project/llvm/include/llvm/ADT/StringMap.h:294:33: error: no match for ‘operator==’ (operand types are ‘std::nullopt_t’ and ‘std::nullopt_t’)
294 |       if (!(KeyValue.getValue() == FindInRHS->getValue()))
```