[X86] Silence an unused-variable warning (NFC)
/llvm-project/llvm/lib/Target/X86/X86AsmPrinter.cpp:188:17:
 error: unused variable 'Triple' [-Werror,-Wunused-variable]
    const auto &Triple = MF.getTarget().getTargetTriple();
                ^
1 error generated.