[AArch64] Remove unused variable 'MaskSize' in GenerateFixedLengthSVETBL (NFC)
/llvm-project/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:26139:12: error: unused variable 'MaskSize' [-Werror,-Wunused-variable]
  unsigned MaskSize = ShuffleMask.size();
           ^
1 error generated.