[ARM] Remove unused variable 'MF' in ARMBaseInstrInfo.cpp (NFC)
/Users/jiefu/llvm-project/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp:4986:24: error: unused variable 'MF' [-Werror,-Wunused-variable]
      MachineFunction &MF = *MBB.getParent();
                       ^
1 error generated.