Revert "Move DroppedVariableStats to CodeGen lib (#120650)"
This reverts commit 95899f06a1a2032a2e52114517a9c76382a8b6c1.

Broke bot ppc64le-clang-multistage-test:

undefined reference to
`llvm::DroppedVariableStats::populateVarIDSetAndInlinedMap in
In function `llvm::DroppedVariableStatsIR::visitEveryInstruction