[MemorySanitizer] Fix an unused-variable warning (NFC)
/llvm-project/llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp:2752:22:
 error: unused variable 'ParamType' [-Werror,-Wunused-variable]
    FixedVectorType *ParamType =
                     ^
1 error generated.