[lldb-dap] Fix a warning
This patch fixes:

  lldb/tools/lldb-dap/lldb-dap.cpp:1405:16: error: comparison of
  integers of different signs: 'int64_t' (aka 'long') and 'size_type'
  (aka 'unsigned long') [-Werror,-Wsign-compare]

(cherry picked from commit e7a43ca84fabeab386ba4d402167244dac27b265)