Revert "[compiler-rt] Avoid memintrinsic calls inserted by the compiler"
This reverts commit a59adb676650ff0a237f2659c6712c1aaa303a3b.

Fails on Mac OS with "sanitizer_libc.cpp:109:5: error: aliases are not
supported on darwin".