Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit 00b0e40fc3504abffb6a8cba04cd31a6c5f20dac.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {