[lldb][test] PlatformDarwinTest.cpp: skip dSYM test on Windows
Fails on Windows with:
```
Script:
--
C:\buildbot\as-builder-10\lldb-x86-64\build\tools\lldb\unittests\Platform\.\LLDBPlatformTests.exe --gtest_filter=PlatformDarwinLocateTest.LocateExecutableScriptingResourcesFromDSYM_SpecialCharactersInModuleName_NoMatch
--
C:\buildbot\as-builder-10\lldb-x86-64\llvm-project\lldb\unittests\Platform\PlatformDarwinTest.cpp(466): error: Expected equality of these values:
  ss.GetString()
    Which is: "warning: the symbol file 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF\\TestModule-1.1 1.o' contains a debug script. However, its name contains reserved characters and as such cannot be loaded. If you intend to have this script loaded, please rename 'c:/buildbot/as-builder-10/lldb-x86-64/build/lit-tmp-yi3ecv47/locate-scripts-from-dsym-test-39be18/.dSYM/Contents/Resources/DWARF/../Python/TestModule-1.1 1.py' to 'c:/buildbot/as-builder-10/lldb-x86-64/build/lit-tmp-yi3ecv47/locate-scripts-from-dsym-test-39be18/.dSYM/Contents/Resources/DWARF/../Python/TestModule_1_1_1.py' and retry.\n"
  expected
    Which is: "warning: the symbol file 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF\\TestModule-1.1 1.o' contains a debug script. However, its name contains reserved characters and as such cannot be loaded. If you intend to have this script loaded, please rename 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF/../Python/TestModule-1.1 1.py' to 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF/../Python/TestModule_1_1_1.py' and retry.\n"
C:\buildbot\as-builder-10\lldb-x86-64\llvm-project\lldb\unittests\Platform\PlatformDarwinTest.cpp:466
Expected equality of these values:
  ss.GetString()
    Which is: "warning: the symbol file 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF\\TestModule-1.1 1.o' contains a debug script. However, its name contains reserved characters and as such cannot be loaded. If you intend to have this script loaded, please rename 'c:/buildbot/as-builder-10/lldb-x86-64/build/lit-tmp-yi3ecv47/locate-scripts-from-dsym-test-39be18/.dSYM/Contents/Resources/DWARF/../Python/TestModule-1.1 1.py' to 'c:/buildbot/as-builder-10/lldb-x86-64/build/lit-tmp-yi3ecv47/locate-scripts-from-dsym-test-39be18/.dSYM/Contents/Resources/DWARF/../Python/TestModule_1_1_1.py' and retry.\n"
  expected
    Which is: "warning: the symbol file 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF\\TestModule-1.1 1.o' contains a debug script. However, its name contains reserved characters and as such cannot be loaded. If you intend to have this script loaded, please rename 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF/../Python/TestModule-1.1 1.py' to 'c:\\buildbot\\as-builder-10\\lldb-x86-64\\build\\lit-tmp-yi3ecv47\\locate-scripts-from-dsym-test-39be18\\.dSYM\\Contents\\Resources\\DWARF/../Python/TestModule_1_1_1.py' and retry.\n"
```

It doesn't make sense to run these on Windows because this is testing dSYM-specific logic (which hard-codes forward slashes to navigate the dSYM directory). Technically we don't even need it on Linux, but since they pass, keep them on there for now.

(cherry picked from commit d6514036002d79fe0a62f266f8b80e7b39ba2e5f)