Revert "[Hexagon] Add instruction definitions for Hexagon v71, v71t, and v73"
This reverts commit e4b00c8158648ae8c8d35040ad58e281424546b8.

The commit caused:

clang/include/clang/Basic/BuiltinsHexagonDep.def:1896:69: error: use of undeclared identifier 'HVXV73'
TARGET_BUILTIN(__builtin_HEXAGON_V6_vadd_sf_bf, "V32iV16iV16i", "", HVXV73)

when building `clang`.