libomptarget: Fix printing garbage in error message
On my system I was hitting this error printing garbage:

ERROR: offload-arch not found for 1002:6658.
WARNING: Runtime capabilities do NOT meet any image offload_arch.
	 So device offloading is now disabled.
	Runtime capabilities : H��]�f�UH��H�}�H�E�HH�	H]�f�
	  Image 0 offload_arch : gfx1031

Now this is changed to:
ERROR: offload-arch not found for 1002:6658.
WARNING: Runtime capabilities do NOT meet any image offload_arch.
	 So device offloading is now disabled.
	Runtime capabilities : (null)
	  Image 0 offload_arch : gfx1031

Change-Id: I7264a8ea88660d3b0043ad6798430ca3099a8eb4