[clang][Driver] Fix libc++ include path on NetBSD
`clang++` defaults to `-stdlib=libc++` on NetBSD.  When building with both
`clang` and `libcxx` included, the freshly built `clang++` fails to find
`<__config_site>`:

```
In file included from /usr/include/strings.h:68:
In file included from bin/../include/c++/v1/string.h:57:
bin/../include/c++/v1/__config:13:10: fatal
error: '__config_site' file not found
   13 | #include <__config_site>
      |          ^~~~~~~~~~~~~~~
```

The file is present in `include/<triplet>/c++/v1`, but that isn't searched
by default.  NetBSD has its own version of addLibCxxIncludePaths which
misses that directory.

Rather than replicating yet another part of the generic version in
`Gnu.cpp`, this patch just calls `Generic_GCC::addLibCxxIncludePaths` from
there.  It keeps to also include `/usr/include/c++`, although this
directory only contains empty directories in my installation.

Tested on `amd64-pc-netbsd10.1`.

I know that this patch also needs testcases (currently there are none that
are affected by this change), but I'd like to get this into the system
first to check that the approach is sound.