[mlir][LLVM] Use int32_t to indirectly construct GEPArg
GEPArg can only be constructed from int32_t and mlir::Value.
Explicitly cast other types (e.g. unsigned, size_t) to int32_t to avoid
narrowing conversion warnings on MSVC. Some recent examples of such are:

mlir\lib\Dialect\LLVMIR\Transforms\TypeConsistency.cpp:
error C2398: Element '1': conversion from 'size_t' to 'T' requires a
narrowing conversion
    with
    [
        T=mlir::LLVM::GEPArg
    ]

mlir\lib\Dialect\LLVMIR\Transforms\TypeConsistency.cpp:
error C2398: Element '1': conversion from 'unsigned int' to 'T' requires a
narrowing conversion
    with
    [
        T=mlir::LLVM::GEPArg
    ]

Co-authored-by: Nikita Kudriavtsev <nikita.kudriavtsev@intel.com>