[llvm] Fix crash with -ir-dump-directory & analysis passes (#202477)
The `StandardInstrumentations` were not filtering out analysis passes
(e.g. `-print-after-all`, etc).

* When printing to `stdout`, this results in additional output that is
unnecessary.
* When using `-ir-dump-directory` because the `PassID` is used for the
filename it results in an invalid file path causing the compiler to
crash. This becomes apparent with `-O1` or higher (e.g. `clang++ -mllvm
-print-before-all -mllvm -ir-dump-directory=dumpdir -O1 -S test.cpp`).

An example of the crash is shown below:
```
fatal error: error in backend: Failed to open dumpdir\18-a1a2011b35962283-module-RequireAnalysisPass<llvm::GlobalsAA, llvm::Module,
      llvm::AnalysisManager<Module>>-before.ll to support -ir-dump-directory: invalid argument
```

Note that with `LLVM_ENABLE_IO_SANDBOX` the error is more ambiguous
showing up as `fatal error: error in backend: IO sandbox violation`.