Revert "Drop upstream divergence in __clang_openmp_device_functions.h"
breaks: accel-v1.4 552 554 557 570

n file included from ep.c:51:
./type.h:4:16: error: expected identifier
    4 | typedef enum { false, true } logical;
      |                ^
/mnt/COD/2023-06-18/aomp_17.0-3/lib/clang/17.0.0/include/stdbool.h:22:15: note: expanded from macro 'false'
   22 | #define false 0
      |               ^

This reverts commit ebd6faa9bb39e67c03e17f6cb0b278b01fb2e84b.

Change-Id: I56e0e4fd10d4790e4f1f4d4315701e33602efd88