Disable TestModuleCXX.test on Windows
Importing cxx modules doesn't seem to work on Windows:

error: a.out :: Class 'tagARRAYDESC' has a member 'tdescElem' of type
  'tagTYPEDESC' which does not have a complete definition.
error: a.out :: Class 'tagPARAMDESCEX' has a member 'varDefaultValue' of type
  'tagVARIANT' which does not have a complete definition.

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@354300 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit c47321f012ad5bedb1071eb549e3c48a16bd5a3c)

apple-llvm-split-commit: b1d1445e58c49ed9c57162816eea9147a91346f9
apple-llvm-split-dir: lldb/