[lldb][test] TestMetadataRegisters.py: add missing include
The macOS Clang-17 matrix bot was failing with:
```
07:33:28  /Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/test/API/macosx/lc-note/additional-registers/add-lcnote.cpp:79:12: error: implicit instantiation of undefined template 'std::vector<unsigned char>'
07:33:28     79 |     payload.resize(payload_str->size(), 0);
07:33:28        |            ^
07:33:28  /Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/include/c++/v1/iosfwd:133:28: note: template is declared here
07:33:28    133 | class _LIBCPP_TEMPLATE_VIS vector;
07:33:28        |                            ^
07:33:28  /Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/test/API/macosx/lc-note/additional-registers/add-lcnote.cpp:80:19: error: implicit instantiation of undefined template 'std::vector<unsigned char>'
07:33:28     80 |     memcpy(payload.data(), payload_str->c_str(), payload_str->size());
07:33:28        |                   ^
07:33:28  /Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/include/c++/v1/iosfwd:133:28: note: template is declared here
07:33:28    133 | class _LIBCPP_TEMPLATE_VIS vector;
07:33:28        |                            ^
07:33:28  /Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/test/API/macosx/lc-note/additional-registers/add-lcnote.cpp:87:12: error: implicit instantiation of undefined template 'std::vector<unsigned char>'
07:33:28     87 |     payload.resize(sb.st_size, 0);
07:33:28        |            ^
07:33:28  /Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/include/c++/v1/iosfwd:133:28: note: template is declared here
07:33:28    133 | class _LIBCPP_TEMPLATE_VIS vector;
```