[offload] - Fix issue with standalone debug offload build
Error: CommandLine Error: Option 'attributor-manifest-internal'
registered more than once

During the standalone debug build of offload the above error is seen
at app runtime when using a prebuilt llvm with LLVM_LINK_LLVM_DYLIB=ON. This
is caused by linking both libLLVM.so and various archives that
are found via llvm_map_components_to_libnames for jit support.