[lldb][AArch64] Fix compilation error in RegisterTypeDetector (#215623)
#214515 introduced a compilation failure on Apple Clang 15:

```
FAILED: tools/lldb/source/Plugins/Process/elf-core/CMakeFiles/lldbPluginProcessElfCore.dir/ThreadElfCore.cpp.o
  In file included from …/src/lldb/source/Plugins/Process/elf-core/ThreadElfCore.cpp:35:
  In file included from …/src/lldb/source/Plugins/Process/elf-core/RegisterContextPOSIXCore_arm64.h:14:
  …/src/lldb/source/Plugins/Process/Utility/RegisterTypeDetector_arm64.h:122:64: error: type 'Args &&' of function parameter pack does not contain any unexpanded parameter packs
      friend const T *Arm64RegisterTypeDetector::MakeType(Args &&...args);
                                                          ~~~~~~~^~~~~~~
  …/src/lldb/source/Plugins/Process/Utility/RegisterTypeDetector_arm64.h:122:48: error: friend declaration of 'MakeType' does not match any declaration in 'lldb_private::Arm64RegisterTypeDetector'
      friend const T *Arm64RegisterTypeDetector::MakeType(Args &&...args);
                                                 ^~~~~~~~
  2 errors generated.
```

This PR moves the type creation into `DetectedTypesHolder` and has
`MakeType` forward to it, so no `friend` declaration is needed.