Revert "[clang] fix getTemplateInstantiationArgs" (#201093)
This caused bootstrap builds on macOS to fail with

  error: definition with same mangled name ... as another definition

in JSONGenerator.cpp. See comments on the original PR.

Reverts llvm/llvm-project#199528