[clang-repl] Fix incorrect "included multiple times" notes
In clang-repl (using in-memory buffers), redefinitions were
incorrectly diagnosed with "included multiple times" notes instead of
"previous definition is here".

This occurred because the check in `Sema::notePreviousDefinition`
compared null FileEntry pointers, treating all in-memory buffers as
the same file.

Before:
```
clang-repl> int a;
clang-repl> int a;
In file included from <<< inputs >>>:1:
input_line_2:1:5: error: redefinition of 'a'
    1 | int a;
      |     ^
<<< inputs >>>:1:1: note: '' included multiple times, additional include site here
<<< inputs >>>:1:1: note: '' included multiple times, additional include site here
error: Parsing failed.
```

After:
```
clang-repl> int a;
clang-repl> int a;
In file included from <<< inputs >>>:1:
input_line_2:1:5: error: redefinition of 'a'
    1 | int a;
      |     ^
input_line_1:1:5: note: previous definition is here
    1 | int a;
      |     ^
error: Parsing failed.
```