[bazel] Add missing deps for #141864 (#142437)
Added in 150d466994050c52db76b64ff2ce44cddddbcad4.

```
external/llvm-project/llvm/include/llvm/Frontend/Driver/CodeGenOptions.h:16:10: error: module llvm-project//llvm:FrontendDriver does not depend on a module exporting 'llvm/Support/Compiler.h'
#include "llvm/Support/Compiler.h"
```