[flang][openmp] Add missing REQUIRES line for -triple amdgcn-amd-amdhsa (#221300)
This fails on build without amd target

```
 error: unable to create target: 'No available targets are compatible with triple "amdgcn-amd-amdhsa"'
```