[llvm-dwp] Emit a clear error when no output file can be determined
Invoking llvm-dwp without -o (and without -e to derive a default name
from) fails deep inside ToolOutputFile with the cryptic message:

    $ /home/smarchi/build/llvm-project/debug/bin/llvm-dwp main.dwo
    while processing dwarf streamer init:
    error: : No such file or directory

Detect this case up front and emit:

    no output file specified (use -o or -e)

which is close to what GNU dwp does:

    dwp: fatal error: no output file specified

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>