Revert "Fix undefined behavior when compiling in C++14 due to sized operator delete"
This reverts commit d9809a260be59170ca45a6cabd30a41c97777ea2.

Due to error: no member named 'operator delete' in
'llvm::TrailingObjects<clang::CodeGen::CGFunctionInfo,
clang::CodeGen::CGFunctionInfoArgInfo>'

apple-llvm-split-commit: dfc34861a6ef4ff117b0cc0a12247e3830bf03d9
apple-llvm-split-dir: clang/