[lldb] Bump shell expansion timeout to fix flaky tests
LLDB launches a small utility program that prints its own arguments to
expand launch arguments. This lldb-argdumper invocation is currently
capped with a 10 second timeout, which is low enough that we keep
hitting it on CI bots in random tests:

```
runCmd failed!
>>> error: shell expansion failed (reason: timed out waiting for shell command to complete). consider launching with 'process launch'.
```

This bumps the timeout to three minutes so we can't hit this even on
very slow machines.